### ISSUE TITLE
Awesome work

### ISSUE THREAD

**Issue by vinjn** [artoolkit/artoolkit5#1]
Thanks Philip for open-sourcing it.

Some initial thoughts for this project, is it possible to separate rendering module from the core tracking module? Then we can make the lib more concise and attract communities like game developers besides Unity since it's already supported :) and creative coders who already have their rendering modules.

**Comment by philip-lamb** [comment]
There is already quite good modularisation and separation of the video acquisition, tracking, and rendering modules, so I'm not sure where you see a need for additional separation. libARgsub and its variants provide basic rendering of the video background and OpenGL projection matrix setup, but model loading and rendering is also separate from this.

There are a number of integrations with other renderers currently available for ARToolKit v2.x, and I would hope that the authors of those integrations would update them for ARToolKit v5.x.

**Comment by vinjn** [comment]
Thanks Philip,

Yes they are already separated in source code level, however these modules live in the same repository. I am suggesting put them to different repositories, core module only deals with tracking algorithm which is platform-independent, and video acquisition is more platform-dependent. We can put libARgsub in its own repository as an official renderer, people can use it or bring their own renderer.
