### ISSUE TITLE
Displaying 3d Object on detect marker

### ISSUE THREAD

**Issue by if412002** [artoolkit/artoolkit5#100]
Excuse me sir,
I have followed this step : https://github.com/kosiara/artoolkit-android-studio-example, and able to detect marker and show the cube object on my apps. I want to replace the cube object with my own object (ex: .obj file). I've imported this project : https://github.com/artoolkit/artoolkit5/tree/master/AndroidStudioProjects/ARSimpleNativeCarsProj but i got this error "java.lang.UnsatisfiedLinkError: Couldn't load ARWrapperNativeCarsExample". 

Can you give me brief explanation how to use my own object and also fix that errors?
Sorry for my bad english, Thank you.

**Comment by hienbx94** [comment]
@if412002 
You need build jni to get ARWrapperNativeCarsExample.so 
Run ndk-build to perform it.

**Comment by marthinpakpahan** [comment]
Thank you for response.
Can u give me some steps to do it, or can u give me your email so i can contact u to ask about this.

**Comment by hienbx94** [comment]
@marthinpakpahan 
I upload a guild video setup it for Android Studio on Youtube.
https://www.youtube.com/watch?v=4NoYMqqIHuA

**Comment by if412002** [comment]
Thank you for the video.
I will try.

**Comment by Kristiansibarani** [comment]
Thankyou @hienbx94 You solve my problem.
You are my hero..
Thankyou for your kindness..

**Comment by ThorstenBux** [comment]
You can also follow the documentation here:
http://artoolkit.org/documentation/doku.php?id=4_Android:android_native

**Comment by renexdev** [comment]
Hi @hienbx94 , could you please update the video link. Unfortunately It's no available any more. Thanks in advance!

**Comment by jeffin07** [comment]
@if412002  did you replace the cube with a 3d model if so can you share your project or give me some advice in how to place a 3d model instead of the cube

**Comment by githubpiyush** [comment]
@oBuiXuanHien Can you update the videos,i want to upload my 3D models which are in obj format plus i want that once marker detected object should stay their and i can interact with it.Any suggestion how to do interaction part and stable modeling once marker detected?Do you have source code for loading obj file on marker?please share it ,Thanks in advance
