### ISSUE TITLE
dataset from on-line location ?

### ISSUE THREAD

**Issue by amet123** [artoolkit/artoolkit5#103]
Is it possible to load 3d content and marker dataset from on-line location ?

**Comment by hienbx94** [comment]
@amet123 
It is possible. 
I try create a server(RoR) to gen marker and android client request to get marker from server.
After detect marker and show content of this marker.

**Comment by amet123** [comment]
Thanks for your quick reply pls ref me some tutorial or link

Thanks

**Comment by hienbx94** [comment]
@amet123 
I don't find any tutorial about change marker and get marker from server.
I try to read code, and find a solution for update marker dynamic.
For ```nftsimpleproj``` example
 - Step 1: Change content of ```markers.data```. It cached on folder cache of application. You need edit line number marker and add new line define new marker.
- Step 2: Download 3 file(iset, fset, fset3) to folder cache/assets/dataNTF.
