### ISSUE TITLE
Pattern read failure in multimarkerconfig

### ISSUE THREAD

**Issue by NuncObdurat** [artoolkit/artoolkit5#105]
Hello, 

I've just downloaded the 5.3.2 version of ARToolkit for Unity, and I am getting an: 
Error opening pattern file 'C:/.../Assets/StreamingAssets\00			' for reading.
message when trying to run the MultimarkerScene sample using the multi-barcode4x3.dat file. 
This is followed by:
Error processing multimarker config file 'C:/.../Assets/StreamingAssets\multi-barcode-4x3.dat': Unable to load pattern 'C:/.../Assets/StreamingAssets\00

My understanding is that if an int such as '00' is specified for each marker in the .dat file, ARToolKit should not have to look for marker pattern files.

Though the single and two marker examples work fine, the multi pattern 4x3 PDF file is not detected at all, I presume due to the failure to load.

**Comment by NuncObdurat** [comment]
I just found that there is whitespace after each of the integer values in the .dat file. 
Removing the whitespace solved the problem. 

I'm not sure if this problem just existed with the Unity distribution.

**Comment by kitizz** [comment]
This was a problem for me too in the OSX v5.3.2 release download

**Comment by Jamsterxop** [comment]
Just for anyone still experiencing this issue, the white space mentioned that you have to delete is after the number assigned to each pattern (i.e. 00, 01, 02).
