### ISSUE TITLE
RELEASE.TXT: No such file or directory Invalid RELEASE.txt

### ISSUE THREAD

**Issue by raphaelbruno** [artoolkit/artoolkit5#106]
Hi, I'm following this video tutorial: https://www.youtube.com/watch?v=GAWyUQ1xaNs
I had unistalled everything and installed again, everything updated until today, as the tutorial teaches.

OS: Elementary OS 0.3.2 Freya (64-bit) (Built on Ubuntu 14.04)
Android Studio 2.0
NDK 12b
ARToolKit 5.3.2

When I run ./build.sh, I got this:
```
Working from directory "[...]/Development/artoolkit5/android".
Building on Linux (x86_64)
cat: [...]/Development/android/sdk/ndk-bundle/RELEASE.TXT: No such file or directory
Invalid RELEASE.txt: 
Android.mk called assert_ndk_version.sh r11: "false"
jni/Android.mk:45: *** NDK version r11 or greater required.  Stop.
Exiting ndk-build script abnormally terminated.
```

I searched RELEASE.TXT file, and really not exists on NDK directory.

**Comment by raphaelbruno** [comment]
Ok, I opened assert_ndk_version.sh file, on line 64 it has this:
```
source_properties="$ANDROID_NDK_ROOT/source.properties"
release_file="$ANDROID_NDK_ROOT/RELEASE.TXT"

#echo "3"
# NDK version r11 and later encode NDK version in source.properties.
if [ -s "$source_properties" ]; then
  version=$(sed -En -e 's/^Pkg.Revision=([0-9a-f]+)/r\1/p' $source_properties)
elif [ -s "$release_file" ]; then
  version=$(grep '^r' $release_file)
else
  # NDK version r4 or earlier doesn't have a RELEASE.txt, and we just asserted
  # that the person was looking for r5 or above, so that implies that this is an
  # invalid version.
  echo false
  exit 0
fi
```

On NDK directory has this file "source.properties":
```
Pkg.Desc = Android NDK
Pkg.Revision = 12.0.2763256-beta1
```

But the script still returns error above. :(

**Comment by raphaelbruno** [comment]
Ok, I got it, on "source.properties" (NDK 12) it has white spaces between equals symbol:
`Pkg.Revision[white space]=[white space]12.0.2763256-beta1`

...and the regex on line 70 (assert_ndk_version.sh) don't works for this, so I just change this original line from:
`  version=$(sed -En -e 's/^Pkg.Revision=([0-9a-f]+)/r\1/p' $source_properties)` 
to this:
`  version=$(sed -En -e 's/^Pkg.Revision\s*=\s*([0-9a-f]+)/r\1/p' $source_properties)`

I just added "\s*" between equals symbol and it works now.

**Comment by philip-lamb** [comment]
Thanks for the feedback. Now patched https://github.com/artoolkit/artoolkit5/commit/7f3438d3f254520b53296c3a6c0e7a6279f7cfaf

**Comment by maclog** [comment]
Hi. I'm following that same video tutorial and the AS_Migration pdf. I also have AS 2 and NDK 12b in a OSX 10.11.4 environment. I've cloned the ARToolkit yesterday (ver 5.3.3) and I still got that same error when "./build.sh". The error is "/Users/nelson/Library/Android/sdk/ndk-bundle/RELEASE.TXT: No such file or directory
Invalid RELEASE.txt:"
Could you please indicate if there are any needed step that I missed?

**Comment by ThorstenBux** [comment]
Having some build issues with Android right now. Will come back to you once I've been able to fix them.

**Comment by ThorstenBux** [comment]
Hi @maclog: There were some build issues see here:
https://github.com/artoolkit/artoolkit5/issues/123

part of it is solved now. Can you please rebase from master again and try.
Let me know if it works for you now.

**Comment by philip-lamb** [comment]
There was an issue with this, where it worked with some versions of 'sed' and not with some others. I've fixed it (finally!) in source now.
