### ISSUE TITLE
Cannot detect Marker on other devices

### ISSUE THREAD

**Issue by if412002** [artoolkit/artoolkit5#107]
Good day sir,
i have followed the instructions on artoolkit documentation on Android platform, and i'm success to implement new project that same with ArSimpleNativeCars. I have tried in Samsung Galaxy S3 device, and it's running well, but when i try in another device, it doesn't work.
There is no error shown but in some time the app being crashed.

I hope you can help me for this problem.
Thank you.

**Comment by ThorstenBux** [comment]
Hi,
There should be an error in the AndroidStudio AndroidMonitor tab (see picture)
<img width="1418" alt="screen shot 2016-04-25 at 10 17 29 pm" src="https://cloud.githubusercontent.com/assets/16772796/14780962/aa04297a-0b33-11e6-8bb1-00cefdd30a0f.png">

You can select the running app in the second dropdown next to the dropdown where you select your device. This filters the log to show only the entries for the selected app.
If you cannot see any error please just copy everything to a text file and make it available. 

Without any further information I fear I cannot help you.

Best
Thorsten

**Comment by if412002** [comment]
Thank you sir for your response,
I didn't get any abnormal error, all of the log is same with a normal log.


Best Regards.

**Comment by ThorstenBux** [comment]
Hi there,

sorry this is really hard to analyse remotely. What kind of device are you using when the app crashes? 

Also you could consider asking the community here:
http://artoolkit.org/community/forums/viewforum.php?f=26

I hope you'll find some solution.

Best
