### ISSUE TITLE
ARmovie for android stop responding after installation android phone

### ISSUE THREAD

**Issue by lya1234** [artoolkit/artoolkit5#112]
i am new to augmented reality artoolkit.. i am running the apk from the androd studio project example.. ARmovie file

**Comment by ThorstenBux** [comment]
Hi,

a bit more input please.
What is your operation system? SDK (version) or GitHub?
Are you running the project from within Android Studio or do you build it (how?) and copy the apk to the phone?

What error message do you get?

Please consider also asking the forum:
http://artoolkit.org/community/forums/viewforum.php?f=26

for help.

**Comment by ThorstenBux** [comment]
@lya1234 : I'm closing this now as I haven't heard back from you in some time. Feel free to open that again if you still have issues.
