### ISSUE TITLE
Integration of ARToolkit SDK in iOS exciting app

### ISSUE THREAD

**Issue by RahaAkhtar** [artoolkit/artoolkit5#12]
Hi 
I want want to integrate ARToolkit sdk in one of my application but i have no idea where to start.
Which file i used from SDK?
How i create trackable ?
Can you please explain the sdk integration process step by step.

Best Regards,
Akhtar

**Comment by philip-lamb** [comment]
Documentation is provided at http://www.artoolkit.org/documentation

**Comment by atrbx5** [comment]
Seriously integrating is quite painfull. why not via pod or framework

**Comment by abdulrahmank** [comment]
Can you give steps to integrate, Documentation doesn't have much steps to integrate sdk with app

**Comment by atrbx5** [comment]
Guys forget about this library it works slow, use Vuforia for free until you can. then pay money for the great product

**Comment by akjesto** [comment]
I also facing an issue for how to integrate ARToolKit library to my new Xcode project in iOS
