### ISSUE TITLE
Build of native example libraries for Android fails on OS X

### ISSUE THREAD

**Issue by peterGraf** [artoolkit/artoolkit5#123]
Hello artoolkit people,

After you fixed #121, I can now successfully compile the shared libraries.
But running the script ./build_native_examples.sh still produces errors.

```
Peters-Mac-mini:android: ./build_native_examples.sh 
Working from directory "/Users/peter/StudioProjects/artoolkit5".
Building on Apple Mac OS X (x86_64)
from /Users/peter/StudioProjects/artoolkit5: going to EclipseProjects/ARSimpleNative
[armeabi] Prebuilt       : libARWrapper.so <= jni/../../../android/libs/armeabi/
[armeabi] Compile++ arm  : ARWrapperNativeExample <= ARWrapperNativeExample.cpp
[armeabi-v7a] Prebuilt       : libARWrapper.so <= jni/../../../android/libs/armeabi-v7a/
[armeabi-v7a] Compile++ arm  : ARWrapperNativeExample <= ARWrapperNativeExample.cpp
[armeabi-v7a] Install        : libc++_shared.so => libs/armeabi-v7a/libc++_shared.so
[x86] Prebuilt       : libARWrapper.so <= jni/../../../android/libs/x86/

... many more successful lines

[mips] SharedLibrary  : libARWrapperNativeCarsExample.so
[mips] Install        : libARWrapperNativeCarsExample.so => libs/mips/libARWrapperNativeCarsExample.so
from /Users/peter/StudioProjects/artoolkit5: going to EclipseProjects/ARNativeES1
[armeabi] Compile++ arm  : ARNativeES1 <= ARNativeES1.cpp
[armeabi] Compile arm    : ARNativeES1 <= ARMarkerSquare.c
[armeabi] StaticLibrary  : libcpufeatures.a
[armeabi-v7a] Compile++ arm  : ARNativeES1 <= ARNativeES1.cpp
[armeabi-v7a] Compile arm    : ARNativeES1 <= ARMarkerSquare.c
jni/ARNativeES1.cpp:457:2: error: no matching function for call to 'arDetectMarker'
        arDetectMarker(arHandle, gVideoFrame);
        ^~~~~~~~~~~~~~
jni/../../../android/../include/AR/ar.h:1045:16: note: candidate function not viable: no known conversion from 'ARUint8 *' (aka 'unsigned char *') to 'AR2VideoBufferT *' for 2nd argument
int            arDetectMarker(ARHandle *arHandle, AR2VideoBufferT *frame);
               ^
1 error generated.
```

Greetings

Peter

**Comment by philip-lamb** [comment]
Android native examples are in the process of being updated for the recent API changes (including arDetectMarker). I'll post here once the update is committed.

**Comment by peterGraf** [comment]
Hello Phillip,

thank you for looking into this, I have the feeling, also from other Android projects I worked with, that the whole Android development environment is too dynamic for being useful. I cannot count the number of AS, SDK and NDK versions I have downloaded during the last year working on Android apps, plus the tools downloaded work with one Java version or another and with one C compiler or another. 

Good luck,

Peter

**Comment by peterGraf** [comment]
Hello,

sorry, I am still stuck on the same problem. I discovered that the examples were updated here on GitHub and downloaded the latest version from here.

But still the build script for the native examples fails, I tried on Win 10, OS X and Ubuntu:

Here is what I get:

./build_native_examples.sh 
Working from directory "/home/peter/AndroidStudioProjects/artoolkit5-master".
Building on Linux (x86_64)
from /home/peter/AndroidStudioProjects/artoolkit5-master: going to AndroidStudioProjects/ARSimpleNativeProj/aRSimpleNative
[armeabi] Prebuilt       : libc++_shared.so <= <NDK>/sources/cxx-stl/llvm-libc++/libs/armeabi/
[armeabi-v7a] Prebuilt       : libc++_shared.so <= <NDK>/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/

... Many lines that show success ...

[x86] StaticLibrary  : libcpufeatures.a
[mips] StaticLibrary  : libcpufeatures.a
[armeabi] SharedLibrary  : libARNativeOSGNative.so
[armeabi-v7a] SharedLibrary  : libARNativeOSGNative.so
jni/../../../../../../android/obj/local/armeabi/libosgdb_deprecated_osg.a(AlphaFunc.o):/Users/phil/Documents/Development/Projects/OpenSceneGraph/Android/osg-git-android/src/osgWrappers/deprecated-dotosg/osg/AlphaFunc.cpp:function _GLOBAL__sub_I_AlphaFunc.cpp: error: relocation overflow in R_ARM_THM_CALL
jni/../../../../../../android/obj/local/armeabi/libosgdb_deprecated_osg.a(AnimationPath.o):/Users/phil/Documents/Development/Projects/OpenSceneGraph/Android/osg-git-android/src/osgWrappers/deprecated-dotosg/osg/AnimationPath.cpp:function _GLOBAL__sub_I_AnimationPath.cpp: error: relocation overflow in R_ARM_THM_CALL

Does anybody know what I could do to fix that problem?

**Comment by ThorstenBux** [comment]
Hi,

yes the integration of OSG into Android isn't working any longer. You can see here and asked the gentleman if he can share his OSG build as it seems that he made it work.
https://github.com/artoolkit/artoolkit5/issues/237#issuecomment-275577148

Cheers
