### ISSUE TITLE
how to add new markers to detect new videos?

### ISSUE THREAD

**Issue by lya1234** [artoolkit/artoolkit5#124]
meaning apps can detect multiple markers. but not the same time.. meaning different markers detect different videos

**Comment by ThorstenBux** [comment]
@lya1234 : I don't get it by you may try in our forum:
http://artoolkit.org/community/forums/index.php

**Comment by lya1234** [comment]
means tht i how to add new marker to detect another video

**Comment by ThorstenBux** [comment]
Hi @lya1234:
please use the forum http://artoolkit.org/community/forums/viewforum.php?f=19 to address such questions. GitHub is used to address bugs and issues inside the ARToolKit.
