### ISSUE TITLE
Bad tracking experience after wrong camera calibration

### ISSUE THREAD

**Issue by the-max0r** [artoolkit/artoolkit5#125]
Hi,

after calibrating the camera of my HTC Nexus 9 tablet (flounder) with [camera calibration app](https://play.google.com/store/apps/details?id=com.artoolworks.ar.utils.calib_camera) according to [http://artoolkit.org/documentation/doku.php?id=4_Android:android_camera_calibration](http://artoolkit.org/documentation/doku.php?id=4_Android:android_camera_calibration), I experience very bad tracking results. I got very bad error values (> 50) but could not prevent them from being uploaded to the cloud service.
My guess: artoolkit now uses these bad calibration parameters, resulting in messed up tracking. Before calibration, everything was fine. I redid the calibration many times, but keep getting bad results.

1. Is it possible to delete or redo these calibration datasets?
2. As a workaround: is it possible to prevent using the camera calibration service?

Thanks in advance! Max

**Comment by the-max0r** [comment]
One possible workaround is to deny the network/internet access in Manifest.xml, but this it not a solution for me. In the following picture, you can see that without calibration (due to denied network access) my object perfectly alignes with the marker:
![screenshot_20160519-175152](https://cloud.githubusercontent.com/assets/8014859/15400327/680df3b4-1deb-11e6-9e45-fa1f01d4380b.jpg)

The second picture shows the same app, just with enabled network access. The alignment is totally distorted and the object jumps heavily when moving the tablet:
![screenshot_20160519-175343](https://cloud.githubusercontent.com/assets/8014859/15400532/1d88e4ba-1dec-11e6-969a-4b8fa9378aea.jpg)

With network access, the log shows:
```
I/libar: cparamSearch beginning search for htc/Nexus 9/flounder, camera 0, aspect ratio 4:3.
I/libar: Fetched 8 camera calibration records from online database.
I/libar: Matched fetched camera calibration record (1280x960, 0.00).
I/libar: Matched fetched camera calibration record (640x480, 0.00).
```

**Comment by Death111** [comment]
Hey,
do you have the same experience when using the calibration tool (see #131) and therefore get high error values?

**Comment by the-max0r** [comment]
Hi Death111, I can confirm this and commented also in #131.
