### ISSUE TITLE
iPhone 6S and 6S plus configuration files not available

### ISSUE THREAD

**Issue by chsherali** [artoolkit/artoolkit5#13]
@philip-lamb Amazing stuff you are doing here. I am using your NFT solution in one of my projects on test basis and It has amazing results. There is a problem though that ARToolkit for iOS doesn't support iPhone 6S and 6S+ yet. 
Can you please guide me how can we calibrate new iDevices or is there any new update in pipeline?

**Comment by pteasima** [comment]
Bump. Has anyone solved this?

**Comment by BoiseBaked** [comment]
@Bump Are you referring to iPhone 6 support or the NFT multi marker crash #104 (ARSimpleNativeCars example app built on Ubuntu Linux to target Android)? Because the iPhone 6 is supported.

**Comment by pteasima** [comment]
Sorry, I was reffering to this issue, i.e. ARToolkit support on ip 6s and 6s+. Im sorry but I only have two devices available and thats the 6s and 6s+. I cant see anything other than the camera feed when I run any of the examples.
