### ISSUE TITLE
DeadLock in threadFree

### ISSUE THREAD

**Issue by arkeon7** [artoolkit/artoolkit5#132]
In the threadFree function from the artoolkit5/lib/SRC/Util/thread_sub.c file
the same mutex is locked twice ending in a dead lock

current code:
pthread_cond_destroy(&((*flag)->cond1));
pthread_cond_destroy(&((*flag)->cond1));

should be:
pthread_cond_destroy(&((*flag)->cond1));
pthread_cond_destroy(&((*flag)->cond2));

**Comment by philip-lamb** [comment]
You're right that this is a bug, but it wouldn't produce a deadlock. At worst, the second condition variable wouldn't be freed. Regardless, nice catch, and I'll get a fix in.
