### ISSUE TITLE
possible crash when an NFT marker pyramid do not find any feature point

### ISSUE THREAD

**Issue by arkeon7** [artoolkit/artoolkit5#133]
I ran into this while using the current frame dynamically to train a marker.
sometimes the last pyramid level is just too small to detect any good feature.

```
Index: lib/SRC/KPM/kpmMatching.cpp
===================================================================
--- lib/SRC/KPM/kpmMatching.cpp	(revision 8763)
+++ lib/SRC/KPM/kpmMatching.cpp	(revision 8764)
@@ -299,7 +299,11 @@
                     }
                 }
                 ARLOGi("points-%d\n", points.size());
-               kpmHandle->pageIDs[db_id] = kpmHandle->refDataSet.pageInfo[k].pageNo; kpmHandle->freakMatcher->addFreakFeaturesAndDescriptors(points,descriptors,points_3d,kpmHandle->refDataSet.pageInfo[k].imageInfo[m].width,kpmHandle->refDataSet.pageInfo[k].imageInfo[m].height,db_id++);
+                if (points.size() > 0)
+                {
+                  kpmHandle->pageIDs[db_id] = kpmHandle->refDataSet.pageInfo[k].pageNo;
+                  kpmHandle->freakMatcher->addFreakFeaturesAndDescriptors(points, descriptors, points_3d, kpmHandle->refDataSet.pageInfo[k].imageInfo[m].width, kpmHandle->refDataSet.pageInfo[k].imageInfo[m].height, db_id++);
+                }
             }
         }
     }
```

**Comment by Neuroforge** [comment]
Hello,

Are you able to include the image you are using? What image sizes are you using for training?

**Comment by arkeon7** [comment]
yes the generated marker works correctly with this correction.
it's just prevent a crash in next functions calls.

the frame used to generate the marker is 240px width.
main code here for info : http://redmine.scolring.org/projects/scol/repository/entry/scol/plugins/bitmapToolkit/src/ArTkMarker.cpp

**Comment by SilviyaRepo** [comment]
Hi ,

I have to download 100 markers on view load and have to update the same with 5-10 markers at the time of first marker scan.

Downloading a marker and reading reference set was quite easy for the first time.

But when it comes to update kpmHandle with updated referenceset I am getting error like ' ID already exist'.
This error coming after reading first point .,
Below I mentioned the crash log

points-123
libc++abi.dylib: terminating with uncaught exception of type vision::Exception: ID already exists



Error Description:
1. On first time LoadNFT executes well without crash
2. Same loadNFT with existing markers+ new markers reference set and then [self LoadNFT] ======== > CRASH

**Comment by mlostekk** [comment]
Did you find a solution?
