### ISSUE TITLE
Facing Problem after run nftBookProj sample project unable to run in 

### ISSUE THREAD

**Issue by amet123** [artoolkit/artoolkit5#134]
Facing Problem after run nftBookProj sample project unable to run in 
Nexus 5 ( OpenGL ES 3.0  Adreno ™ 330 )  : Working 
Lenovo K2 Note  ( Android 5.0 with   OpenGL ES 3.1 Mali-T760 )  : Not Working
Motrola 4g ( OpenGL ES 3.0  Adreno ™ 305 )  : Not Working 

I didn't  Understand

Thanks

**Comment by ThorstenBux** [comment]
Did you run the plain sample project or did you change anything?
Did you get any error message?

Are you running the project on the phone from Android Studio or how do you build and deploy it to the phone?

Which OS are you using for development?

Best
Thorsten

**Comment by amet123** [comment]
i am just running plain project without any changes with Android Studio during Compile he ask me to change jdk1.7   nothing else i do 

Thanks

**Comment by ThorstenBux** [comment]
Which JDK are you using? Just curious as I never got asked about the JDK.

Any error messages?

Which operating system (Mac, Linux, Windows) and version?

**Comment by amet123** [comment]
i tell you about changes i have done during Compile
JDK 1.7 i use , no Error Message , Window 10 I use 
OpenGL 2.0 Working Very Well my Problem with OpenGl 3.0

**Comment by amet123** [comment]
In OpenGL 3.0 Screen Show Black Druring application Run

**Comment by ThorstenBux** [comment]
Ok, I never tried with OpenGL ES 3.0. Did you change the settings in the manifest?

<uses-feature android:glEsVersion="0x00010100" /> (default)

Would be great if you could give me as many details about that as possible. So I can run some test.

**Comment by amet123** [comment]
I done with Default Setting thats it , 
I am confuse motrola4g and nexus 5 both same OpenGL 3.0 but running in nexus 5 only

**Comment by ThorstenBux** [comment]
Now I get confused what you are doing.

Can you maybe list step by step procedures?
