### ISSUE TITLE
artoolkit5 has any limitation in the amount of polygons

### ISSUE THREAD

**Issue by amet123** [artoolkit/artoolkit5#135]
Hello,

I'm trying to make a 3D model with animation .if artoolkit5 has any limitation in the amount of polygons a model can have in order to maintain a good performance or Max limitation of polygon ?

Thanks,

**Comment by philip-lamb** [comment]
This is not an ARToolKit-related dependency. Test with your preferred devices and see. In the past we have used models with up to 1 million polys without problems on desktop CPUs.

**Comment by amet123** [comment]
what about mobile and Unity ??
