### ISSUE TITLE
how to draw the bounding box rectangle of nft marker？

### ISSUE THREAD

**Issue by yujinfu** [artoolkit/artoolkit5#137]
Hi , I am new in AR and artoolkit library, 
I want to ask how to draw the bounding box of nft marker(nft image)
when the nft marker is matched and tracking,no mather the whole nft image
or just one part of it is in the range of phone camera.
if anybody have same question ,open talking here.
if anyone know how to acheive it ,please help me,thanks very much.
so sorry for my poor English.

**Comment by yujinfu** [comment]
Hi, can anybody help me?

**Comment by norips** [comment]
Hi I manage to do it by modifying ARWrapper, I have make a pull request. You can check it out here  : #203 
And how to use it, you can see an example on my repo [here](https://github.com/norips/ProjetComAR/blob/ff5f128804a30a69634c3c82806392488da1b6ae/ARSimpleProj/aRSimple/src/main/java/org/artoolkit/ar/samples/ARSimple/SimpleRenderer.java#L111) .

Feel free to ask :smile_cat:

**Comment by yujinfu** [comment]
Hi @norips , thanks for your answer. 
but what I said was how to draw bounding rectangle of nft marker not marker patt or marker board.
Do you know how to achieve that?

**Comment by norips** [comment]
Look at the example I use NFT Marker look line **76**.
If you want to draw the bounding box just draw 4 lines like this : 
```
Line 1 : (0,0,0) (width,0,0) //Bottom line
Line 2 : (0,0,0) (0,height,0) //Left line
Line 3 : (width,0,0) (width,height,0) //Right line
Line 4 : (0,height,0) (width,height,0) //Top line
```

**Comment by yujinfu** [comment]
Hi norips, thanks very much. I will try that.

**Comment by ThorstenBux** [comment]
Closing as I guess it was fixed due to no more questions.

**Comment by DellCliff** [comment]
Hi norips, could you build the modified aRBaseLib.aar and libARWrapper.so for android ? I have no clue how to do it myself.
