### ISSUE TITLE
Unity iOS XCode linker fail

### ISSUE THREAD

**Issue by NeedNap** [artoolkit/artoolkit5#145]
I can't build the test scene, exported from Unity 4.7, into XCode 7.3.1.

I always get the following linker errors:

Undefined symbols for architecture armv7:
  "std::__1::__shared_weak_count::~__shared_weak_count()", referenced from:
      std::__1::__shared_ptr_pointer<vision::Keyframe<96>*, std::__1::default_delete<vision::Keyframe<96> >, std::__1::allocator<vision::Keyframe<96> > >::~__shared_ptr_pointer() in libARWrapper.a(libARWrapper.a-armv7-master.o)
      std::__1::__shared_ptr_pointer<vision::Keyframe<96>*, std::__1::default_delete<vision::Keyframe<96> >, std::__1::allocator<vision::Keyframe<96> > >::~__shared_ptr_pointer() in libARWrapper.a(libARWrapper.a-armv7-master.o)
      std::__1::__shared_ptr_pointer<unsigned char*, NullArrayDeleter<unsigned char>, std::__1::allocator<unsigned char> >::~__shared_ptr_pointer() in libARWrapper.a(libARWrapper.a-armv7-master.o)
      std::__1::__shared_ptr_pointer<unsigned char*, NullArrayDeleter<unsigned char>, std::__1::allocator<unsigned char> >::~__shared_ptr_pointer() in libARWrapper.a(libARWrapper.a-armv7-master.o)
      std::__1::__shared_ptr_pointer<unsigned char*, std::__1::default_delete<unsigned char>, std::__1::allocator<unsigned char> >::~__shared_ptr_pointer() in libARWrapper.a(libARWrapper.a-armv7-master.o)
      std::__1::__shared_ptr_pointer<unsigned char*, std::__1::default_delete<unsigned char>, std::__1::allocator<unsigned char> >::~__shared_ptr_pointer() in libARWrapper.a(libARWrapper.a-armv7-master.o)
  "std::__1::basic_ostream<char, std::__1::char_traits<char> >::sentry::sentry(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)", referenced from:
      std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::__put_character_sequence<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, char const*, unsigned long) in libARWrapper.a(libARWrapper.a-armv7-master.o)

...
...

I imported manually the ARToolkit library into Unity 4.7 and made some adjustments to the c sharp code to support UNITY_4_7 version.
It works fine in Unity Editor but I can't deploy on my iPhone.

Do you have any tips to solve my problem?
Thanks

**Comment by ThorstenBux** [comment]
Hi there,

I'm sorry but we currently only support up to date Unity versions. So I'm unable to give support on that topic.
You can try the forum for help : http://artoolkit.org/community/forums/viewforum.php?f=28

**Comment by BoiseBaked** [comment]
The errors you are seeing here are because you linking old static libraries where header files were compiled to target and linked to target the GNU C++/libc++ runtime while the newer ARTK static libraries and the current Android NDK target Clang++/libstdc++ runtime.

**Comment by NeedNap** [comment]
Thank you BoiseBaked, is there a trick to use Unity 4.x or I must update my license to the 5.x version?
I'll update Unity soon, but now I have a dead line on a AR project that uses Vuforia, with some issues on very large marker, so I would like to use ARToolkit.
