### ISSUE TITLE
Old version OpenSSL

### ISSUE THREAD

**Issue by Chourizo** [artoolkit/artoolkit5#146]
This is not really a bug, but If I am not mistaken the libARWrapper.so at the Unitypackage of ARToolkit is using:
OpenSSL 1.0.1o 12 Jun 2015

And Google Play do not allow apps woth OpenSSL older than 1.01r due to the Heartbleed bug. All google play apps will not be updated if it contains this old version after July 11th.

From google:
Please migrate your app(s) to OpenSSL 1.02f/1.01r or higher as soon as possible and increment the version number of the upgraded APK. Beginning July 11, 2016, Google Play will block publishing of any new apps or updates that use older versions of OpenSSL. Your published app version will remain unaffected, however any updates to the app will be blocked unless they address this vulnerability.

**Comment by ThorstenBux** [comment]
Hi there,

can you for now use the version provided on GitHub. There the update of SSL is already done. We just didn't package a new release jet.

Best

**Comment by Chourizo** [comment]
I will do that. Thanks for your answer.
