### ISSUE TITLE
ARToolkit  replece obj

### ISSUE THREAD

**Issue by maryjaho** [artoolkit/artoolkit5#151]
Hi.
I am running artoolkit sample named ARSimpleNativeCars.
I want to replace cars with my own 3d model.
Is it enough to edit cpp native file?
I did so, but it didnt work.
Can anyone help me?
#52

**Comment by Divoo** [comment]
- Open the terminal in `ARSimpleNativeCarsProj/aRSimpleNativeCars/src/main`
- Type 
```
$ ndk-build clean all
$ ndk-build
```
- Clear the installed app data or Re-install it

**Comment by maryjaho** [comment]
Thanks for your answer,
But when I do so, terminal says:
"ndk-build is not recognized as an internal or external command, operable program or batch file"
Whats the problem?

**Comment by Divoo** [comment]
Your PATH should include the root directory of your NDK.
in Linux add this line to your `~/.bashrc`:
```
export PATH=$PATH:/path/to/ndk
```
for example in my machine
```
export PATH=$PATH:/home/divoo/Android/Sdk/ndk-bundle
```
then restart your machine or type in terminal:
```
source ~/.bashrc
```

**Comment by maryjaho** [comment]
I am on windows..Is there any way to do it on windows?

**Comment by Divoo** [comment]
Change PATH from here `MyComputer->Properties->Advanced->Env Variables->Path`

OR

```
set PATH=%PATH%;C:\path\to\ndk
```

I didn't try this on Windows machine but it should work

**Comment by maryjaho** [comment]
Thank you so much for your help.

**Comment by SanjithKanagavel** [comment]
JPG files are only allowed in obj texture and they seem to crash for files large than 5 mb in android.

**Comment by maryjaho** [comment]
really?
That`s too bad..if so, in android we cant use good quality objects. is there any solution?

**Comment by ThorstenBux** [comment]
No solution yet for the texture files. Sorry guys

**Comment by SanjithKanagavel** [comment]
PS : It worked for all sizes. I was mistaken. ARToolkit at it's best. 💃
