### ISSUE TITLE
Examples are compliling and running but highlight errors in Android Studio

### ISSUE THREAD

**Issue by Divoo** [artoolkit/artoolkit5#152]
When I import any example, it **highlights errors** in `.cpp` file.

![android-studio](https://cloud.githubusercontent.com/assets/4347943/16932651/6e06547a-4d50-11e6-8be9-1beb1815c8b6.png)

From the errors in the file:
- On first `JNIFUNCTION_DEMO`: `Error after macro substitution: Can't resolve type 'Java_org_artoolkit_ar_samples_ARSimpleNativeCars_SimpleNativeRenderer_demoInitialise'`
- A lot of `unexpected symbol`

Although the example is **compiling correctly** and working, but because of this problem all of the editing features are not working like auto-complete.

I thought Android Studio doesn't support _c++_ and _jni_ yet, so I tried _hello_jni_ example and it's working perfectly without highlighting errors.

I spent all day trying to fix the problem but I couldn't find any solution.
Is any one having this ? How to solve it ?

My OS is Fedora 24.
I build ARToolkit from master.

**Comment by ThorstenBux** [comment]
Hi @Divoo I'm currently trying to hunt that down. So if you get to build if from within android studio let me know. Currently only the ndk-build with the Android.mk and Application.mk file is supported.

**Comment by ThorstenBux** [comment]
There is a way to remove the highlighted errors. You need to include the path to the includes files in the build.gradle of your project. Here is an example how I did it:
```
    android.ndk {
        moduleName = "calibration_upload_native"
        cppFlags.add("-std=c++11")
        cppFlags.add("-fexceptions")
        cppFlags.add("-frtti")
        cppFlags.add("-DDEBUG")
        debuggable = true
        toolchain = "clang"
        ldLibs.addAll(['GLESv1_CM', 'log', 'z'])
        platformVersion 15
        stl 'c++_shared'
        abiFilters.add("x86")
        abiFilters.add("armeabi")
        abiFilters.add("armeabi-v7a")
        abiFilters.add("mips")
        cppFlags.add('-I' + file("/Users/thorstenbux/DAQRI/gitHub/artoolkit5-dev/include"))
        cppFlags.add('-I' + file("/Users/thorstenbux/DAQRI/gitHub/artoolkit5-dev/include/android"))
        cppFlags.add('-I' + file("/Users/thorstenbux/DAQRI/gitHub/artoolkit5-dev/android/jni/curl/include"))
        //CFlags.add("-I${file("/Users/thorstenbux/DAQRI/gitHub/artoolkit5-dev/include")}".toString())
    }
}


tasks.all {
    task ->
        if (task.name.startsWith('compile') && task.name.contains('MainC')) {
            task.enabled = false
        }
        if (task.name.startsWith('link')) {
            task.enabled = false
        }
        if (task.name.endsWith('SharedLibrary') ) {
            task.dependsOn ndkBuild
        }
}

task ndkBuild(type: Exec, description: 'Compile JNI source via NDK') {
    def ndkDir
    doFirst {
        ndkDir = System.getenv('ANDROID_NDK_ROOT')
        if (null == ndkDir) {
            Properties properties = new Properties()
            properties.load(project.rootProject.file('local.properties').newDataInputStream())
            ndkDir = properties.getProperty('ndk.dir', null)
        }
        if (null == ndkDir)
            throw new TaskExecutionException("NDK Directory not found. Define location with ndk.dir in the local.properties file or with an ANDROID_NDK_ROOT environment variable.")
        else
            println "ndkDir var set to: $ndkDir"

        // Requires for the org.apache.tools.ant.taskdefs.condition.Os import
        if (Os.isFamily(Os.FAMILY_WINDOWS)) {
            println 'Trying to execute ndk-build.cmd'
            commandLine '$ndkDir/ndk-build.cmd', '-C', file('src/main').absolutePath
        } else {
            println 'Trying to execute ndk-build'
            commandLine "$ndkDir/ndk-build",'NDK_DEBUG=1','V=1','-C', file('src/main/jni').absolutePath
        }
    }
}
```
This also includes calling ndk-build from the gradle file. So no need to call it manually anymore. This still has some flaws, but at least the highlighted errors are gone.
