### ISSUE TITLE
Visualize PATT Files

### ISSUE THREAD

**Issue by muhammedyusuf-sermet** [artoolkit/artoolkit5#153]
Hi,

I'm trying to test the ARDistanceOpenGLES20Proj example from the website. I compiled and ran it, but where can I find the markers that has been used in this example? There are 2 .patt files called "cat" and "minion", but I failed to visualize those.

Thanks

**Comment by ThorstenBux** [comment]
You are right, somehow they are not in the repo anymore:

Here you go

![catpattern_10pxborder](https://cloud.githubusercontent.com/assets/16772796/17037503/63beb7f4-4fe5-11e6-9169-8b80a3eb9475.png)
![minionpattern_10pxborder](https://cloud.githubusercontent.com/assets/16772796/17037504/63c05bae-4fe5-11e6-9540-e84442c76685.png)

**Comment by muhammedyusuf-sermet** [comment]
Excellent! Thanks for the fast response.

**Comment by renexdev** [comment]
Thanks @ThorstenBux!

**Comment by ThorstenBux** [comment]
You are welcome 😀. Share your awesome apps if you can?

**Comment by renexdev** [comment]
I'm learning the Framework for android Studio right now. By the moment I'm trying to compile all samples and understand a little how AR works. When I got something interesting for sure I'll share!
