### ISSUE TITLE
Is it possible to use AR without markers?

### ISSUE THREAD

**Issue by MicroDroid** [artoolkit/artoolkit5#154]
I had certain coordinates for objects and I want to draw them on the screen.

i.e., Once the user scans some QR code, he will get coordinates for nearby objects, the coordinates are like:

```
ObjectA:
    x: 120
    y: 80
    z: 130
```

These x/y/z are degrees. this example data means the object should exist in 120 degrees on the x axis, 80 on the y, and 120 on the z

-----

You can think of it like drawing on the screen based on predefined coordinates rather than markers. Is that possible?

**Comment by SanjithKanagavel** [comment]
Its possible through SLAM Technology !

**Comment by ThorstenBux** [comment]
That is not possible with ARToolKit right now. But as @SanjithKanagavel mentioned there are other ways to do that.
