### ISSUE TITLE
How to call Java method from C++ using JNI in ARtoolkit?

### ISSUE THREAD

**Issue by hasanaliqureshi** [artoolkit/artoolkit5#155]
can anyone give me a step by step procedure how can I achieve it. I've tried many methods but nothing's working.

**Comment by ThorstenBux** [comment]
ARToolKit contains many examples how to call C++ from Java but now the other way round. Also, I'm not sure if this is an ARToolKit related issue of just a C++, Java, JNI issue. 

I'll close this but please open it again if it is indeed a ARToolKit issue or if you would like to share how you approached and hopefully fixed it by now.

**Comment by BoiseBaked** [comment]
Hasan, If that is your name, pardon me if it isn't. I assume you're wondering how do a C++ call to Java over JNI, really reverse-JNI, for the Android platform. It's definitely possible and some of the ARToolKit example apps implement it. But really, you should Google for the technique. There's a vast number tutorials on the Internet. Trying to help others come up to speed on Augmented Reality on multiple platforms is hard enough for us. We just don't have the bandwidth answer questions of this scale.
