### ISSUE TITLE
example_simplelite documentation has escaped </pre> tag in text

### ISSUE THREAD

**Issue by FlashSheridan** [artoolkit/artoolkit5#158]
The documentation page “simpleLite - The First Example Application to Look At”  (http://artoolkit.org/documentation/doku.php?id=7_Examples:example_simplelite) displays an escaped HTML &lt;/pre&gt;  tag in the text, at the beginning of the last paragraph of the “main” section:

> &lt;/pre&gt; The third major part of ARToolKit

Here’s the source; note that the incorrect escaped tag displayed in the text is preceded by a correct unescaped tag:

`   arUtilTimerReset();</pre>`
`&lt;/pre&gt;`

`The third major part of ARToolKit`

**Comment by ThorstenBux** [comment]
Will be fixed with the next website release
