### ISSUE TITLE
Link text makes sentence ungrammatical in “Installing ARToolKit” documentation web page 

### ISSUE THREAD

**Issue by FlashSheridan** [artoolkit/artoolkit5#159]
In the “Mac OS X / Linux” section of the “Installing ARToolKit” documentation page (http://artoolkit.org/documentation/doku.php?id=1_Getting_Started:about_installing), the displayed text for the link to the “Setting an Environment Variable” page conflicts with the surrounding text:

> to set the [Setting an Environment Variable](http://artoolkit.org/documentation/doku.php?id=1_Getting_Started:general_environment_variables), open a Terminal window

Here’s the HTML source:

`to set the <a href="/documentation/doku.php?id=1_Getting_Started:general_environment_variables" class="wikilink1" title="1_Getting_Started:general_environment_variables">Setting an Environment Variable</a>, open a Terminal window`

I would suggest replacing “Setting an Environment Variable” with “environment variables”.

**Comment by ThorstenBux** [comment]
That is already fixed: 
https://github.com/artoolkit/artoolkit-docs/edit/master/1_Getting_Started/about_installing.md

But not rendered on the website yet. I'll trigger an update.
