### ISSUE TITLE
Error opening pattern file 'Data/patt.hiro' for reading.

### ISSUE THREAD

**Issue by raghavSrih** [artoolkit/artoolkit5#16]
Hi,

When I create a new android project which exactly replicates the ARSimple project I get the below error in the logcat and then application crashes.

"Error opening pattern file 'Data/patt.hiro' for reading."

I have the pattern files in my project assets folder and I have changed the version number as well.
I could't figure what the issue is for past 1 week.

Regards,
Raghav

**Comment by philip-lamb** [comment]
Is it perhaps the asset caching? Increment the version number integer and the cache will refresh on next launch.

**Comment by raghavSrih** [comment]
I did increment the version number. It did not work

**Comment by balintgaspar** [comment]
Same happenind in new project on iOS

**Comment by barrievince** [comment]
I was having the same problem. I created the ARSimpleApplication and assigned it in the manifest. That corrected the problem.

It looks like the initializeInstance method uses the AssetHelper to make the files available in the data folder.

**Comment by sebitas** [comment]
I have the same problem in IOS project, any suggestions?

**Comment by ThorstenBux** [comment]
Closing as this issues is very old and we just released the 5.3.2 version. If anyone still has this issue please ping and I open it again.
