### ISSUE TITLE
Link to nonexistent ios_system_support page in “ARToolKit for iOS” documentation page

### ISSUE THREAD

**Issue by FlashSheridan** [artoolkit/artoolkit5#160]
The “[ARToolKit for iOS](http://artoolkit.org/documentation/doku.php?id=5_iOS:ios_about)” documentation page starts with a link to “ios_system_support” (http://artoolkit.org/documentation/doku.php?id=5_iOS:ios_system_support), which says “This topic does not exist yet.”

**Comment by ThorstenBux** [comment]
Thanks for letting us know. I removed the link for now:
https://github.com/artoolkit/artoolkit-docs/pull/27
