### ISSUE TITLE
Mac OS X instructions in “Executing simpleLite” won’t work with default security settings

### ISSUE THREAD

**Issue by FlashSheridan** [artoolkit/artoolkit5#161]
The “Executing simpleLite/Mac OS X” subsection of [simpleLite - The First Example Application to Look At](http://artoolkit.org/documentation/doku.php?id=7_Examples:example_simplelite) says:

> double-click the simpleLite.app example app

If the Security & Privacy system preference for “Allow apps downloaded from” is set to “Mac App Store and identified developers” (which I believe is the default), this will result in an error dialog:

> … can’t be opened because it is from an unidentified developer.

I suggest that the instructions should instead say:

> Control-click the simpleLite.app example app, and press Open in the ensuing dialog.

Configuration: ARToolKit5-bin-5.3.2r1-OSX, MacOS 10.11.6 15G31

**Comment by ThorstenBux** [comment]
Created a PR:
https://github.com/artoolkit/artoolkit-docs/pull/26
