### ISSUE TITLE
glutGet etc. deprecated in OS X 10.9 and later

### ISSUE THREAD

**Issue by FlashSheridan** [artoolkit/artoolkit5#162]
Compiling simpleLite.c gives 19 deprecation warnings for glutGet and 16 other functions:
<br>
`4> cc simpleLite.c -c -I  ../../include  -o simpleLite`
`simpleLite.c:376:7: warning: 'glutGet' is deprecated: first deprecated in OS X 10.9 [-Wdeprecated-declarations]`
`        ms = glutGet(GLUT_ELAPSED_TIME);`
`             ^`
`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/GLUT.framework/Headers/glut.h:545:21: note: `
`      'glutGet' has been explicitly marked deprecated here`
`extern int APIENTRY glutGet(GLenum type) OPENGL_DEPRECATED(10_0, 10_9);`
`                    ^`
`simpleLite.c:423:3: warning: 'glutPostRedisplay' is deprecated: first deprecated in OS X 10.9 [-Wdeprecated-declarations]`
`                glutPostRedisplay();`
`                ^`
`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/GLUT.framework/Headers/glut.h:444:22: note: `
`      'glutPostRedisplay' has been explicitly marked deprecated here`
`extern void APIENTRY glutPostRedisplay(void) OPENGL_DEPRECATED(10_0, 10_9);`
`                     ^`
…

<br>
This agrees with https://developer.apple.com/library/prerelease/content/releasenotes/General/APIDiffsMacOSX10_9/GLUT.html.   Here’s the list of functions warned about: glutBitmapCharacter, glutBitmapLength, glutCreateWindow, glutDisplayFunc, glutEnterGameMode, glutGameModeString, glutGet, glutIdleFunc, glutInit, glutInitDisplayMode, glutInitWindowSize, glutKeyboardFunc, glutMainLoop, glutPostRedisplay, glutReshapeFunc, glutSwapBuffers, glutVisibilityFunc.

<br>
Configuration: ARToolKit5-bin-5.3.2r1-OSX, MacOS 10.11.6 15G31, Xcode 7.3 Build version 7D175, Apple LLVM version 7.3.0 (clang-703.0.29)

**Comment by ThorstenBux** [comment]
Hi, thanks for letting us know. That should be fixed with the ARToolKit 6 release.
