### ISSUE TITLE
Android App crashing

### ISSUE THREAD

**Issue by SanjithKanagavel** [artoolkit/artoolkit5#165]
Android App crashing while loading new obj file. It gives no error. I tried to increase heap space also. Dosen't work. Crashes at once marker is identified. Why aren't png files not supported in obj textures ??

**Comment by ThorstenBux** [comment]
Can you post a logcat output to see what happens before the crash? Also to really try and support here I'd need the app project code.

**Comment by SanjithKanagavel** [comment]
Actually it worked again when i tried. Thanks @ThorstenBux 👍
