### ISSUE TITLE
Help required in animating objects

### ISSUE THREAD

**Issue by SanjithKanagavel** [artoolkit/artoolkit5#168]
Hello,
I wish to animate objects using ARToolkit. OSG examples were one of them that helps in animating. How can i achieve animation? How to use vrml animations here ? any sample projects for animation ?
@ThorstenBux @philip-lamb Please help me sir.

**Comment by ThorstenBux** [comment]
Hi,
I'd go with the Unity plug-in and make the animation within Unity and export it for there to your platform.

**Comment by SanjithKanagavel** [comment]
Thanks Thorsten :)
