### ISSUE TITLE
Downloading calibration file

### ISSUE THREAD

**Issue by behrooz-tahanzadeh** [artoolkit/artoolkit5#169]
How can I download calibration file for my phone from [https://omega.artoolworks.com/app/calib_camera/download.php]()? What's the parameters that I should provide?

I need to have the file locally since I'm working only on one device which doesn't have access to network.

Thanks...

**Comment by ThorstenBux** [comment]
Hi,

as of now the Android App that you build with ARToolKit will fetch the calibration automatically from the server. The download.php is not designed to use manually. We will fix all that in the ARToolKit6 release. 

Kind regards
Thorsten Bux
