### ISSUE TITLE
How to develope App using ARToolkit

### ISSUE THREAD

**Issue by maryjaho** [artoolkit/artoolkit5#170]
Hello,
I am working with aRToolkitSampleNativeCars and I want to replace the obj (ferrari & porsch) with my own obj.
but its not possible and it didnt recognize my obj and again load its obj(ferrari and porsch).
I ran ndk-build.cmd and increased version code. but it didnt work.
Does anyone know whats the problem?

**Comment by ThorstenBux** [comment]
Are you running in AndroidStudio? That builds the app automatically so no need for you to run ndk-build.cmd manually. 
Also can you please post your logcat output.

**Comment by MarlonFerri** [comment]
I had a lot of problems to use ARToolkit with Android Studio, but they are
my fault.
One problem that I had to change default obj was simple to resolve. If you
already install and run the sample project into a device, you need to
uninstall it first, that change the obj in correct folder, change cpp code
with your own. Do not forget to build it again. So you can install again
and run with your own obj without problem.

Any doubts, I'll be happy to help in your start with Android Studio.

2016-09-18 16:01 GMT-03:00 Thorsten Bux <notifications@github.com>:

**Comment by ThorstenBux** [comment]
Thanks for the reply will close this now.
Cheers
