### ISSUE TITLE
fix marker always-on display?

### ISSUE THREAD

**Issue by iampkuhz** [artoolkit/artoolkit5#171]
hi, I'm using artoolkit to develog android app. 

I want to put a static marker(would not be moved) on the table and draw a cube in a relative site corresponding to the marker (may be far away from the marker). I want to make the cube visible once the marker is found and keep the cube visible even the marker is no longer in the camera.

what i realy want is when I turn the camera back to marker, the cube would be display smoothly, instead of jump onto the screen once the whole marker is detected.

I'm tried almost all the androidstudio demo in the example list and it seems no relavent ones.

How can I do this? 
It would be great if there is a dem about this!

**Comment by zhuyiif** [comment]
setup the right matrix for cube, and draw it
`	if (1) {
	      gPatt_trans[0][0] = 0.65525454331394872f;

        gPatt_trans[0][1] = -0.2077755761361248f;

        gPatt_trans[0][2] = -0.72627184540482503f;

        gPatt_trans[0][3] = 14.772836385089299;

        

        gPatt_trans[1][0] = -0.33138619588408336f;

        gPatt_trans[1][1] = -0.94304350400646342f;

        gPatt_trans[1][2] = -0.029191415325181595f;

        gPatt_trans[1][3] = -12.953451598870616f;

        

        gPatt_trans[2][0] = -0.67884068281438792f;

        gPatt_trans[2][1] = 0.25980427154400731f;

        gPatt_trans[2][2] = -0.68678749831631547f;

        gPatt_trans[2][3] = 398.60723010561719f;
		// Calculate the camera position relative to the marker.
		// Replace VIEW_SCALEFACTOR with 1.0 to make one drawing unit equal to 1.0 ARToolKit units (usually millimeters).
		arglCameraViewRH((const ARdouble (*)[4])gPatt_trans, m, VIEW_SCALEFACTOR);
#ifdef ARDOUBLE_IS_FLOAT
        glLoadMatrixf(m);
#else
        glLoadMatrixd(m);
#endif

		// All lighting and geometry to be drawn relative to the marker goes here.
		DrawCube();
	
	} // gPatt_found
`

**Comment by ThorstenBux** [comment]
Hi @iampkuhz ,

were you able to fix your issue?

**Comment by iampkuhz** [comment]
I was not able to make this and currently not work on this issue.

However, I found someone else using unity3d made a similar demo (draw object without marker always inside screen)
