### ISSUE TITLE
How can I record camera and 3D model ?

### ISSUE THREAD

**Issue by zhangchioulin** [artoolkit/artoolkit5#172]
Hi, I think the artoolkit is a very good tool. 
but how can I record  camera and 3D model?
Can i record 'glView' content or you provide any method?

thank you provide us this tool.

**Comment by ThorstenBux** [comment]
Hi,

ARToolKit does not provide a screen capturing tool. I use ScreenFlow on the Mac most of the time and AndroidTool to capture the Android screen.

Best
Thorsten
