### ISSUE TITLE
(Android Studio) handleUncaughtException(): exception type, java.lang.UnsatisfiedLinkError: Couldn't load c++_shared from loader dalvik.system.PathClassLoader[DexPathList[[zip f

### ISSUE THREAD

**Issue by aresares** [artoolkit/artoolkit5#186]
**Hi i'm trying to run ARSimpleProject, it compile successfuly but when it run it give this error _(i have not change anything ,i just downloaded and compiled)_:**

`09-02 19:28:08.495 28401-28401/org.artoolkit.ar.samples.ARSimple E/ARBaseLib::ARActivity: handleUncaughtException(): exception type, java.lang.UnsatisfiedLinkError: Couldn't load c++_shared from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.artoolkit.ar.samples.ARSimple-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.artoolkit.ar.samples.ARSimple-1, /vendor/lib, /system/lib]]]: findLibrary returned null

09-02 19:28:08.495 28401-28401/org.artoolkit.ar.samples.ARSimple E/ARBaseLib::ARActivity: handleUncaughtException(): thread, "main" exception, "Couldn't load c++_shared from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.artoolkit.ar.samples.ARSimple-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.artoolkit.ar.samples.ARSimple-1, /vendor/lib, /system/lib]]]: findLibrary returned null"`

**The rest of the log:**

09-02 19:28:08.495 28401-28401/org.artoolkit.ar.samples.ARSimple W/System.err: java.lang.UnsatisfiedLinkError: Couldn't load c++_shared from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.artoolkit.ar.samples.ARSimple-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.artoolkit.ar.samples.ARSimple-1, /vendor/lib, /system/lib]]]: findLibrary returned null
09-02 19:28:08.495 28401-28401/org.artoolkit.ar.samples.ARSimple W/System.err:     at java.lang.Runtime.loadLibrary(Runtime.java:358)
09-02 19:28:08.500 28401-28401/org.artoolkit.ar.samples.ARSimple W/System.err:     at java.lang.System.loadLibrary(System.java:526)
09-02 19:28:08.500 28401-28401/org.artoolkit.ar.samples.ARSimple W/System.err:     at org.artoolkit.ar.base.NativeInterface.loadNativeLibrary(NativeInterface.java:69)
09-02 19:28:08.500 28401-28401/org.artoolkit.ar.samples.ARSimple W/System.err:     at org.artoolkit.ar.base.ARToolKit.<clinit>(ARToolKit.java:68)
09-02 19:28:08.500 28401-28401/org.artoolkit.ar.samples.ARSimple W/System.err:     at org.artoolkit.ar.base.ARActivity.onStart(ARActivity.java:193)
09-02 19:28:08.500 28401-28401/org.artoolkit.ar.samples.ARSimple W/System.err:     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
09-02 19:28:08.500 28401-28401/org.artoolkit.ar.samples.ARSimple W/System.err:     at android.app.Activity.performStart(Activity.java:5241)
09-02 19:28:08.500 28401-28401/org.artoolkit.ar.samples.ARSimple W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2178)
09-02 19:28:08.500 28401-28401/org.artoolkit.ar.samples.ARSimple W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2271)
09-02 19:28:08.500 28401-28401/org.artoolkit.ar.samples.ARSimple W/System.err:     at android.app.ActivityThread.access$800(ActivityThread.java:144)
09-02 19:28:08.500 28401-28401/org.artoolkit.ar.samples.ARSimple W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
09-02 19:28:08.500 28401-28401/org.artoolkit.ar.samples.ARSimple W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
09-02 19:28:08.500 28401-28401/org.artoolkit.ar.samples.ARSimple W/System.err:     at android.os.Looper.loop(Looper.java:136)
09-02 19:28:08.500 28401-28401/org.artoolkit.ar.samples.ARSimple W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5146)
09-02 19:28:08.500 28401-28401/org.artoolkit.ar.samples.ARSimple W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
09-02 19:28:08.500 28401-28401/org.artoolkit.ar.samples.ARSimple W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
09-02 19:28:08.500 28401-28401/org.artoolkit.ar.samples.ARSimple W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
09-02 19:28:08.500 28401-28401/org.artoolkit.ar.samples.ARSimple W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
09-02 19:28:08.505 28401-28401/org.artoolkit.ar.samples.ARSimple W/System.err:     at dalvik.system.NativeStart.main(Native Method)

**Comment by BoiseBaked** [comment]
The error to pay attention to is: "Couldn't load c++_shared from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.artoolkit.ar.samples.ARSimple-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.artoolkit.ar.samples.ARSimple-1, /vendor/lib, /system/lib]]]: findLibrary returned null." The .apk file is zip file that contains the app that is deployed to the device. You didn't build the ARToolKit native lib dependencies, dependencies of all the example apps. Please go to the Android specific ARToolKit Online Documentation and look for "build.sh" and "build_native_examples.sh." I'm assuming your building on Mac OS X.

**Comment by ThorstenBux** [comment]
http://artoolkit.org/documentation/doku.php?id=4_Android:android_native
these are the steps to follow

**Comment by LamdaSofia** [comment]
Hey guys, i have the same problem, and everyone keeps posting this as a solution. The thing is that it doesnt open (file not found)...

**Comment by srichandis** [comment]
Can someone create the content of what was in http://artoolkit.org/documentation/doku.php?id=4_Android:android_native at another place?

**Comment by ThorstenBux** [comment]
probably this: https://github.com/artoolkit/artoolkit-docs/blob/master/4_Android/android_native.md
