### ISSUE TITLE
(Android Studio) Work only with Hiro marker not with a,b,c,d ...

### ISSUE THREAD

**Issue by aresares** [artoolkit/artoolkit5#188]
Hi, i compiled the ARSimpleProj project on AndroidStudio/Windows and it worked well for some time but now it dosen't recognize the other markers like a,b,c,d ... anymore , it  only recognize the **Hiro** marker ,when i try the other markers i don't get nothing, for example i tried marker **B** but nothing, i haven't modified the code since last time that it worked ,it's strange
![b](https://cloud.githubusercontent.com/assets/15111793/18254712/eeeade6e-73a0-11e6-8c5c-670658b7d04e.png)

`	@Override
	public boolean configureARScene() {

		markerID = ARToolKit.getInstance().addMarker("single;Data/patt.hiro;80");
		//markerID = ARToolKit.getInstance().addMarker("single;Data/multi/patt.b;80");
		if (markerID < 0) return false;

		return true;

	}`

Im using a Smasung Galaxy S3

Any idea of what can be the problem? (maybe camera parameters configuration? )

**Comment by ThorstenBux** [comment]
One thing you can try is to uninstall the app and install it again on your phone. Android Studio does not redeploy the app (or at least the res directory) if the version number stays the same. 
You could also try and change the version code and number.
Or modify the run configuration to install the APK regardless of code changes or not.

Let me know if that helps

**Comment by BoiseBaked** [comment]
Plus, I don't know how long ago you pulled the ARToolKit SDK or Repo but we stopped naming the pattern files with leading file extensions a while back:
Data/patt.hiro -> Data/hiro.patt
Data/multi/patt.b ->Data/multi/b.patt

**Comment by aresares** [comment]
Thx **ThorstenBux** i changed the version code number and it worked, uninstalling and reinstalling app doesn't work.

**BoiseBaked** i used this [https://github.com/kosiara/artoolkit-android-studio-example](url) that has jniLibs compiled
