### ISSUE TITLE
No Installation Rule...

### ISSUE THREAD

**Issue by jiapei100** [artoolkit/artoolkit5#196]
So, should there be a installation for artoolkit5???

> ========================= Installation results ===========================
> make: **\* No rule to make target 'install'.  Stop.
> 
> ***\*  Installation failed. Aborting package creation.
> 
> Cleaning up...OK
> 
> Bye.

Thank you....

**Comment by ThorstenBux** [comment]
Hi,

can you please be a bit more precise? I have no idea what you are trying to tell us.

**Comment by jiapei100** [comment]
Ok... 

My operating system: Ubuntu 16.04.1

After successfully configure and make artoolkit5, I want to install artoolkit5 to some particular directory, normally it should be /usr/local. That is to say: normally, the artoolkit5 SDK will be installed under /usr/local/ by default. However, I got the following error mesage while trying to do **make install**


```
jiapei:artoolkit5$ make install
make: *** No rule to make target 'install'.  Stop.
```

## It looks this version of artoolkit5 does NOT support Linux?

Cheers

**Comment by ThorstenBux** [comment]
Can you share more information about your Configuration and how you configured ARTK5. I'm sure it compiles on Ubuntu 16.04 as I did that myself.

**Comment by philip-lamb** [comment]
@jiapei100  Linux is supported, but there is no install target in the makefile, as the build is done in-tree.
