### ISSUE TITLE
Can't build native examples

### ISSUE THREAD

**Issue by norips** [artoolkit/artoolkit5#199]
Hi, I can't build native examples, build.sh work great but when I try to launch build_native_examples.sh
it throw this kind of error :

> jni/../../../../../../android/obj/local/armeabi/libosgdb_deprecated_osg.a(NodeCallback.o):/Users/phil/Documents/Development/Projects/OpenSceneGraph/Android/osg-git-android/src/osgWrappers/deprecated-dotosg/osg/
> NodeCallback.cpp:function NodeCallback_readLocalData(osg::Object&, osgDB::Input&): error: undefined reference to '__cxa_bad_cast'
> 
> jni/../../../../../../android/obj/local/armeabi/libosgdb_deprecated_osg.a(NodeCallback.o):/Users/phil/Documents/Development/Projects/OpenSceneGraph/Android/osg-git-android/src/osgWrappers/deprecated-dotosg/osg/
> NodeCallback.cpp:function _GLOBAL__sub_I_NodeCallback.cpp: error: relocation overflow in R_ARM_THM_CALL

**Info:**
NDK version : 13
OS : Ubuntu 16.04

**Comment by ThorstenBux** [comment]
Yes, OpenSceneGraph integration is currently broken. We will take care of this in ARToolKit 6, which will be launched soon.
