### ISSUE TITLE
Bug in genTexData  ("DPI, in range [-1.#IO, -1.000]")

### ISSUE THREAD

**Issue by RichardCMulder** [artoolkit/artoolkit5#2]
The current version of genTexData fails to read images, causing behavior such as reported on the forums here: 
http://artoolkit.org/community/forums/viewtopic.php?f=29&t=4536&p=7523 and 
http://artoolkit.org/community/forums/viewtopic.php?f=22&t=1775&p=7522

The issue is in https://github.com/artoolkit/artoolkit5/blob/master/util/genTexData/genTexData.c#L595
```if (!filename || !image_p || !*image_p || !xsize_p || !ysize_p || !nc_p || !dpi_p) return (E_BAD_PARAMETER);```

I believe this line should be: 
```if (!filename || !image_p || !xsize_p || !ysize_p || !nc_p || !dpi_p) return (E_BAD_PARAMETER);```

Because image (to which image_p is a pointer), will, at this point in the execution, always be NULL.

In addition, the E_BAD_PARAMETER result value is never checked (see https://github.com/artoolkit/artoolkit5/blob/master/util/genTexData/genTexData.c#L344 ), causing the confusing error behavior.

**Comment by philip-lamb** [comment]
Well spotted. I will push a fix shortly.

**Comment by philip-lamb** [comment]
Fixed in 14109caca4d8f77c25fe36f2c8e3c493c7743514.
