### ISSUE TITLE
User provided marker images

### ISSUE THREAD

**Issue by oney** [artoolkit/artoolkit5#201]
Thanks for all awesome works!
Is it possible that users take a picture on smartphone and the app takes this image as marker?

**Comment by ThorstenBux** [comment]
Hi,
there is an OpenSpace3D example where they do exactly that:
https://youtu.be/vSF1ZH1CwQI?list=UUQENrJg8qszKMSXILPkwRHQ

You can look there to find out how they did it.
Right now it is now feature that is directly included into ARToolKit

**Comment by oney** [comment]
Thanks for the response.
However, it seems that the link you gave has to use the software on PC. Can I do all things on the smartphone by using ARToolKit?

**Comment by ThorstenBux** [comment]
Yes you can do those things on the smartphone too. Actually you can export to Android from OpenSpace3D.
