### ISSUE TITLE
Dynamic adding marker does not work

### ISSUE THREAD

**Issue by tuandt** [artoolkit/artoolkit5#208]
Hi,

I am working on a project that require to add markers dynamic (NFT markers).

I tried 2 ways:
1. Download all NFT marker files (.fset, iset, fset3) to a folder. Creat markers.dat file then call:

String configMarkerString = "multi;"+baseFolder.getPath() +"/Data/markers.dat";
int markerID = ARToolKit.getInstance().addMarker(configMarkerString);
1. Download all NFT marker files (.fset, iset, fset3) to cache folder. Creat markers.dat file then call:

String configMarkerString = "multi;"+ cacheFolderPath +"/Data/markers.dat";
int markerID = ARToolKit.getInstance().addMarker(configMarkerString);

Both of them return markerID = -1.

Did anyone can dynamic add NFT like that?
Does anyone have solution for this problem?

I will appreciate a lot.

**Comment by norips** [comment]
Hi,
Where do you call addMarker method ?

**Comment by tuandt** [comment]
Hi,

Sorry, what do you mean by "where"?

In my project. I will have to download NFT makers files from server.

After finish downloading, I call add maker function.

**Comment by norips** [comment]
By where I mean in which function do you call it, are you sure nft thread
is initialised, ARWrapper does not show you some error when you call
addMarker ?

**Comment by tuandt** [comment]
Hi Norips,

Thank you for your reply. I am sure that nft thread is initialised. ARWrapper does not show me any error. It just returns -1. I think it's because I am using native library.

Have you been able to add dynamic markers ever?

**Comment by norips** [comment]
Hi, I download marker from a server too, on the end of the download I call addMarker for each downloaded marker, in one time.
Trying to do add marker while there were already marker crash the program sending a SiGINT signal.
So I think there is a bug. Wait for dev to answer :smile: I think there are working on the new version of artoolkit

**Comment by norips** [comment]
Maybe if you provide some code, other people can help you, best is the entire project on a repo.

**Comment by tuandt** [comment]
Here is my source code:

https://github.com/tuandt/ARMovieProj

Actually, I edited from ARMovieProj example.

Hope that some one can help.

**Comment by harakuru99** [comment]
Any news on this topic?

**Comment by jonesjeff** [comment]
I hope I understand your problem correctly but it is possible to add markers dynamically. First you need to add an ARMarker script to your scene, here I have called it "myMarker". Then you need to configure it to the settings you want. Then you must add it to the list of tracked markers in the AROrigin script. Finally you must update your ARTrackedObject. Here is the full documentation https://artoolkit.org/documentation/doku.php?id=6_Unity:unity_low_level_api

`void LoadMarkers(string markerTag, string dataName, GameObject markerRoot){
	myMarker = ARToolKit.gameObject.AddComponent<ARMarker>();

	// Configure
	myMarker.Tag = markerTag;
	myMarker.MarkerType = MarkerType.NFT;
	myMarker.NFTDataName = dataName;
	myMarker.Filtered = true;
	myMarker.Load();

	//Add marker to list
	myAROrigin.AddMarker(myMarker);

	// Update ARtracked Object
	myARTrackedObject = markerRoot.GetComponent<ARTrackedObject>();
	myARTrackedObject.MarkerTag = markerTag;
	}`

**Comment by jonesjeff** [comment]
I hope I understand your problem correctly but it is possible to add markers dynamically. First you need to add an ARMarker script to your scene, here I have called it "myMarker". Then you need to configure it to the settings you want. Then you must add it to the list of tracked markers in the AROrigin script. Finally you must update your ARTrackedObject. Here is the full documentation https://artoolkit.org/documentation/doku.php?id=6_Unity:unity_low_level_api

```
void LoadMarkers(string markerTag, string dataName, GameObject markerRoot){
myMarker = ARToolKit.gameObject.AddComponent();

// Configure
myMarker.Tag = markerTag;
myMarker.MarkerType = MarkerType.NFT;
myMarker.NFTDataName = dataName;
myMarker.Filtered = true;
myMarker.Load();

//Add marker to list
myAROrigin.AddMarker(myMarker);

// Update ARtracked Object
myARTrackedObject = markerRoot.GetComponent<ARTrackedObject>();
myARTrackedObject.MarkerTag = markerTag;
}`
```

**Comment by ThorstenBux** [comment]
Nice solution, thanks
