### ISSUE TITLE
SimpleLite not opening(Linux)

### ISSUE THREAD

**Issue by HybridXY** [artoolkit/artoolkit5#210]
I just installed ArtoolKit 5.3.2 and im currently checking its functionality by trying to run the simpleLite example in the bin directory.

When I ran ./simpleLite I got the following error: 
./simpleLite: error while loading shared libraries: libglut.so.3: cannot open shared object file: No such file or directory
Any suggestions to how i might resolve this issue?

**Comment by ThorstenBux** [comment]
I guess you are missing the GLUT dependency:

sudo apt-get install freeglut3-dev

In general the dependencies are listed here: 
http://artoolkit.org/documentation/doku.php?id=8_Advanced_Topics:build_artoolkit
