### ISSUE TITLE
Can not import project to AndroidStudio

### ISSUE THREAD

**Issue by aresares** [artoolkit/artoolkit5#212]
Hi, i'm trying to import projects like ARSimpleProj or ARMultiProj to AndroidStudio but can't, everything block (not freeze) on "Building 'ARSimpleProj' Gradle project info". I have everything updated to last version. Gradle version: com.android.tools.build:gradle:2.2.2

**Comment by ThorstenBux** [comment]
Do you have error messages or screen shots?

**Comment by BoiseBaked** [comment]
Why are importing the projects? They're standalone Android Studio project already. If you want to import the module in those Android Studio projects into your AS project, that's a different story. Not sure what you're doing. Enumerate your steps in more detail.

**Comment by aresares** [comment]
Those are the steps that i follow to import ARSimpleProj:
![senzanome](https://cloud.githubusercontent.com/assets/15111793/20244519/25c2c94a-a986-11e6-92eb-4a74976101aa.png)

**Comment by aresares** [comment]
it's working now, i don't know why but it's working
Thx

**Comment by BoiseBaked** [comment]
You don't import Android Studio projects. You open projects. You can, if you want, import a module from a project, like ARSimpleProj, into another project, in various ways.
