### ISSUE TITLE
QtKit is no longer supported on XCode8

### ISSUE THREAD

**Issue by jmhobrien** [artoolkit/artoolkit5#214]
I'm unable to build genMarkerSet under XCode 8 on Sierra. The genMarkerSet target reports `'QTKit/QTKit.h' file not found`

It looks like QTKit support was removed from Xcode 8. Current workaround seems to be to install the OSX 10.11 package for QTKit:
https://forum.openframeworks.cc/t/macos-10-12-sierra-xcode-8-quicktime-deprecation-workaround/24179/8

Perhaps there is some other way to build on OSX which I am not aware of?

**Comment by ThorstenBux** [comment]
Hi @jmhobrien,

unfortunately you need to downgrade XCode to 7.x right now to build ARTK5 on Mac. Good news is that the issue will be fixed in ARToolKit6.

Here you can download the previous XCode version.
https://developer.apple.com/download/more/
