### ISSUE TITLE
How to get the camera_para.dat after calibration camera(Android devices) by the "ARToolKit Camera Calibrator" app?

### ISSUE THREAD

**Issue by Yongzili** [artoolkit/artoolkit5#217]
I use "ARToolKit Camera Calibrator" app to calibration Android device camera,when I complete the calibration work, I want to get the  camera_para.dat , but I do not know how to get it.It would be very grateful if someone could help.

**Comment by ThorstenBux** [comment]
Hi @Yongzili ,
unfortunately as of now ARToolKit camera calibration app does only store the camera calibration on the server. Each time an app with ARToolKit starts up this server is queried and the camera calibration is downloaded to the device. 
We will change that with ARToolKit6 camera calibration app.

**Comment by Yongzili** [comment]
Hi @ThorstenBux ,
thanks for reply,look forward to the ARToolKit6 camera calibration app.But I still have a question , if I got the camera_para.dat,can I put the camera_para.dat in my unity project, so as to avoid get the file from service,because it took a long time to get the camera_para.dat from service,  and during the request, my android device screen display black.
Expect to receive a reply,thanks very much.

**Comment by ThorstenBux** [comment]
Yes, you can add it to your Unity project.

**Comment by Yongzili** [comment]
I add the camera_para.dat to Unity project,but it still get from server.I put the file under the folder :Assets/ARToolkit5-Unity/Resources/ardata/. Did I put the wrong place?

**Comment by ThorstenBux** [comment]
Did you rename it to: .bytes?

**Comment by Yongzili** [comment]
Hi @ThorstenBux,
I have rename it to:.bytes.
And one more question, every time i open the app, upper left corner of the screen show a square preview, how  to close it?

**Comment by ThorstenBux** [comment]
Hi,

there exists no function currently to take it out. It should be possible to remove it is you change the flow how it is currently handled and open the video only when you need it. That might require some more changes inside the code. We are working on fixing that for the upcoming ARToolkit6 release.

**Comment by Yongzili** [comment]
Ok,thank you very much @ThorstenBux 
The last question is when to release the ARToolkit6 ?
