### ISSUE TITLE
Question: How to remove a marker?

### ISSUE THREAD

**Issue by aresares** [artoolkit/artoolkit5#220]
Hi, is it possible to remove a marker once we added it like `ARToolKit.getInstance().addMarker("single;Data/mult.....`
 exists the corresponding 
`ARToolKit.getInstance().removeMarker(...)`

Thx

**Comment by ThorstenBux** [comment]
Hi,

is is here:
https://github.com/artoolkit/artoolkit5/blob/master/AndroidStudioProjects/ARBaseLibProj/aRBaseLib/src/main/java/org/artoolkit/ar/base/NativeInterface.java#L262

You would need to integrate it into the ARToolKit facade class: https://github.com/artoolkit/artoolkit5/blob/master/AndroidStudioProjects/ARBaseLibProj/aRBaseLib/src/main/java/org/artoolkit/ar/base/ARToolKit.java

Cheers
