### ISSUE TITLE
openssl warning from playstore not able to publish app

### ISSUE THREAD

**Issue by shashank2001** [artoolkit/artoolkit5#221]
this is the reason i was given not able to publis the app
OpenSSL
The vulnerabilities were addressed in OpenSSL 1.02f/1.01r. To confirm your OpenSSL version, you can do a grep search for:

$ unzip -p YourApp.apk | strings | grep "OpenSSL"

please help me out ,still the files are not updated in new unity package

**Comment by ThorstenBux** [comment]
Does that help? https://github.com/artoolkit/artoolkit5/issues/215
