### ISSUE TITLE
ARSimpleInteraction Sample app is showing black screen only

### ISSUE THREAD

**Issue by abhisek-mishra** [artoolkit/artoolkit5#222]
Hi,
While Debugging this application on my MOTOE , it shows only black screen, I am pasting the debug logs below, it seems it is unable to load a native library.. Any help or clue ? I tried ARSimpleProj too but there also same behavior, am I missing any basic step ?  Thanks a lot to you all for your help and guidance..

E/ARBaseLib::ARActivity: handleUncaughtException(): exception type, java.lang.UnsatisfiedLinkError: Couldn't load c++_shared from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.artoolkit.ar.samples.ARSimpleInteraction-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.artoolkit.ar.samples.ARSimpleInteraction-1, /vendor/lib, /system/lib]]]: findLibrary returned null
E/ARBaseLib::ARActivity: handleUncaughtException(): thread, "main" exception, "Couldn't load c++_shared from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.artoolkit.ar.samples.ARSimpleInteraction-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.artoolkit.ar.samples.ARSimpleInteraction-1, /vendor/lib, /system/lib]]]: findLibrary returned null"
W/System.err: java.lang.UnsatisfiedLinkError: Couldn't load c++_shared from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.artoolkit.ar.samples.ARSimpleInteraction-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.artoolkit.ar.samples.ARSimpleInteraction-1, /vendor/lib, /system/lib]]]: findLibrary returned null
W/System.err:     at java.lang.Runtime.loadLibrary(Runtime.java:358)
W/System.err:     at java.lang.System.loadLibrary(System.java:526)
W/System.err:     at org.artoolkit.ar.base.NativeInterface.loadNativeLibrary(NativeInterface.java:69)
W/System.err:     at org.artoolkit.ar.base.ARToolKit.<clinit>(ARToolKit.java:68)
W/System.err:     at org.artoolkit.ar.base.ARActivity.onStart(ARActivity.java:193)
W/System.err:     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1194)
W/System.err:     at android.app.Activity.performStart(Activity.java:5258)
W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2171)
W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)
W/System.err:     at android.app.ActivityThread.access$800(ActivityThread.java:139)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err:     at android.os.Looper.loop(Looper.java:136)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5086)
W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
W/System.err:     at dalvik.system.NativeStart.main(Native Method)

**Comment by ThorstenBux** [comment]
Hi,
you need to run the ./build.sh and from the android directory. This script build and preloads the Android projects with the native libraries.

See here: http://artoolkit.org/documentation/doku.php?id=4_Android:android_native

**Comment by abhisek-mishra** [comment]
Thanks a lot, it worked like a charm ...
