### ISSUE TITLE
The problem of ASimpleNativeCarsProj

### ISSUE THREAD

**Issue by OtakuAndFitness** [artoolkit/artoolkit5#223]
I succeed to run this example on Android but when I use camera to point to Hiro pattern.pdf, nothing happens. Basically there will be a car loaded, right?

**Comment by ThorstenBux** [comment]
Can you please past a logcat output here?
Otherwise we cannot help you

**Comment by OtakuAndFitness** [comment]
Thanks for replying. Unfortunately my boss said "we don't use artoolkit".

**Comment by ThorstenBux** [comment]
Perfect :)
