### ISSUE TITLE
Unity Engine crashed because of Artoolkit Unitypackage 5.3.2

### ISSUE THREAD

**Issue by sankyprabhu** [artoolkit/artoolkit5#227]
whenever I import ARToolki Unitypackage 5.3.2 my Unity Engine get crashed and to recover from this I have to reinstall Unity again 
Its a really serios problem, because reinstalling Unity is heavy task and I done it 2 times only because of ARtoolkit Unitypackage

PFA: Image Of Unity console

Error Log Report : UNetWeaver error: Method ReadInt64
UnityEngine.Debug:LogError(Object)
Unity.UNetWeaver.Log:Error(String) (at /Users/builduser/buildslave/unity/build/Extensions/Networking/Weaver/Program.cs:20)
Unity.UNetWeaver.Weaver:ResolveMethod(TypeReference, String) (at /Users/builduser/buildslave/unity/build/Extensions/Networking/Weaver/UNetWeaver.cs:1093)
Unity.UNetWeaver.Weaver:SetupReadFunctions() (at /Users/builduser/buildslave/unity/build/Extensions/Networking/Weaver/UNetWeaver.cs:1363)
Unity.UNetWeaver.Weaver:Weave(String, IEnumerable`1, IAssemblyResolver, String, String, String) (at /Users/builduser/buildslave/unity/build/Extensions/Networking/Weaver/UNetWeaver.cs:1653)
Unity.UNetWeaver.Weaver:WeaveAssemblies(IEnumerable`1, IEnumerable`1, IAssemblyResolver, String, String, String) (at /Users/builduser/buildslave/unity/build/Extensions/Networking/Weaver/UNetWeaver.cs:1763)
Unity.UNetWeaver.Program:Process(String, String, String, String[], String[], IAssemblyResolver, Action`1, Action`1) (at /Users/builduser/buildslave/unity/build/Extensions/Networking/Weaver/Progr

**Comment by ThorstenBux** [comment]
http://artoolkit.org/community/forums/viewtopic.php?f=28&t=23191

The fix is to upgrade the Unity Editor version to 5.4.1p4, "Patch 5.4.1p4," Released: 5 October 2016, found on this webpage: https://unity3d.com/unity/qa/patch-releases?_ga=1.126870989.110425875.1477066492

**Comment by sankyprabhu** [comment]
Currently working on latest version of Unity 5.5.0f3, Same issue with the current version of Unity  :(

**Comment by ThorstenBux** [comment]
Did you ever try  5.4.1p4
That is the one I can confirm that it works

**Comment by sankyprabhu** [comment]
Fixed: Upgrade Unity to 5.5.0p1
https://unity3d.com/unity/qa/patch-releases?_ga=1.126870989.110425875.1477066492

Thanks :)
