### ISSUE TITLE
Unity Engine crashed because of Artoolkit Unitypackage 5.5.0f3

### ISSUE THREAD

**Issue by sankyprabhu** [artoolkit/artoolkit5#228]
whenever I import ARToolki Unity package 5.5.0f3 my Unity Engine throws many errors

Failed to extract UnityEditor.EditorTestsRunner.TestListTreeViewGUI class of base type UnityEditor.TreeViewGUI when inspecting /Applications/Unity/Unity.app/Contents/UnityExtensions/Unity/EditorTestsRunner/Editor/UnityEditor.EditorTestsRunner.dll
UnityEditor.AssemblyHelper:ExtractAllClassesThatInheritMonoBehaviourAndScriptableObject(String, String[]&, String[]&)

**Comment by ThorstenBux** [comment]
Please place that in the Unity repo: https://github.com/artoolkit/arunity5/issues
