### ISSUE TITLE
js interface?

### ISSUE THREAD

**Issue by haisapan** [artoolkit/artoolkit5#23]
more and more people use js as develop language, like node.js, and js in web. if any possible to provide js API so more people can develop something cool base on it?

**Comment by hienbx94** [comment]
Hi haisapanJsartookit is a JavaScript port of FLARToolKit

**Comment by haisapan** [comment]
Hi @hienbx94, this one? https://github.com/kig/JSARToolKit
I will try it, many thanks

**Comment by philip-lamb** [comment]
We are working on an updated port of JSARToolKit. News coming soon.

**Comment by haisapan** [comment]
if it support Node.JS?
