### ISSUE TITLE
The particle system inside OSG models cannot be rendered properly on both Linux and macOS.

### ISSUE THREAD

**Issue by amalcao** [artoolkit/artoolkit5#237]
Hi!
 I found a problem that when loading an OSG file including the particle systems (provided by osgParticle subsystem), the particle systems, such as smoke and fire, could not been rendered in the simpleOSG app, however, the objects in the same file without any nodes in osgParticle namespace are rendered properly.
For example, if you load the [cessnafire.osg](https://github.com/openscenegraph/OpenSceneGraph-Data/blob/master/cessnafire.osg) file in OpenSceneGraph-data , the cessna is present without any fire. 
I have tested both on Linux (ubuntu 16.04) and macOS (10.12), the problem is same, no matter using the prebuilt one or the one built by myself.
On the contrary, the particle systems just work fine in the android app ARNativeOSG.

I have tried a lot of methods, but the problem still not be solved. Does anyone have the same problem and any solutions? Thanks!

**Comment by peterGraf** [comment]
Hello amalcao, 

sorry, I have no solution for your problem, but rather have a question you might be able to answer.

I downloaded the latest artookit version from here, but I cannot build the ARNativeOSG native examples
with the script 

./build_native_examples.sh

I get an the error shown below: I tried compiling on OSX, Win 10 and Ubuntu, all showed the same problem. You seem to have the ARNativeOSG running, how did you build the libARNativeOSGNative.so?

[armeabi-v7a] SharedLibrary  : libARNativeOSGNative.so
jni/../../../../../../android/obj/local/armeabi/libosgdb_deprecated_osg.a(AlphaFunc.o):/Users/phil/Documents/Development/Projects/OpenSceneGraph/Android/osg-git-android/src/osgWrappers/deprecated-dotosg/osg/AlphaFunc.cpp:function _GLOBAL__sub_I_AlphaFunc.cpp: error: relocation overflow in R_ARM_THM_CALL

**Comment by amalcao** [comment]
In order to fix the linking errors, I've compiled the OpenSceneGraph-3.2.3 by myself and replaced all the OSG static libraries in the artoolkit (which locate in artoolkit/android/obj/). By the way, I've changed the value of `APP_STL` to `gnustl_static` in all `Application.mk` files, I'm not sure if it is necessary.

This method may not be the best solution, but it works for me. 
I think in the new release of artoolkit, the team will fix this BUG.

Good Luck!

**Comment by ThorstenBux** [comment]
Thanks for sharing your result on that

**Comment by amalcao** [comment]
I found a naive solution for this issue, taking the simpleOSG.app as an example, I just add two lines to the function `Display()` in file `simpleOSG.cpp` as below just before calling the `VirtualEnvironmentHandleARViewDrawPreCamera()` :
```
   glEnableClientState(GL_VERTEX_ARRAY);
   glEnableClientState(GL_TEXTURE_COORD_ARRAY);
```

I think the issue may be caused by such client-side capabilities are disabled during rendering the background image stream captured by the camera, and they are not reenabled by OSG particle system while drawing.

I hope this will help others who have the same problem.
