### ISSUE TITLE
Unsupported method: AndroidProject.getPluginGeneration()

### ISSUE THREAD

**Issue by darshanpopat** [artoolkit/artoolkit5#238]
When I try to run ARSimpleNativeCarsProj, I get an error Unsupported method: AndroidProject.getPluginGeneration() and it not getting my project run.

**Comment by BoiseBaked** [comment]
AndroidProject.getPluginGeneration() is an Android Studio runtime feature. I suggest you hit developer.android.com, the search engines and stackoverflow for work around. This might be a start: 
http://stackoverflow.com/questions/39591531/unsupported-method-androidproject-getplugingeneration-while-running-project/39591532
