### ISSUE TITLE
Anywhere for me to specify installation prefix?

### ISSUE THREAD

**Issue by jiapei100** [artoolkit/artoolkit5#239]
Hi, all:

I've successfully built artoolkit5, however, doesn't it come with an installation?

Cheers
Pei

**Comment by BoiseBaked** [comment]
Not sure what an "installation prefix" is but ARToolkit is an SDK, not a finished application. The SDK can be downloaded in two forms: 1) cloned as a repo of source that build into libraries or as a zip file where the source builds into libraries. The libraries are dependencies for AR apps. The app installer needs to include the built ARToolKit dependencies.
