### ISSUE TITLE
Inverted Textures in OBJ/MTL 3D Model.

### ISSUE THREAD

**Issue by joaoamaral** [artoolkit/artoolkit5#24]
I used a OBJ/MTL Object from Three.js (female02) that renders correctly on Xcode (OBJ visualizer in Xcode - image1) but in ARApp the textures are strange (image2). Did anyone else also found this problem? Is there a quickfix?
Thank you.

Image 1
<img width="1512" alt="image1" src="https://cloud.githubusercontent.com/assets/147158/11525444/771d2384-9916-11e5-9c69-843bdb73a65c.png">

Image 2
![image2](https://cloud.githubusercontent.com/assets/147158/11525443/76e839e4-9916-11e5-9f0e-3b428d31bfa5.png)

**Comment by dk00891** [comment]
hi joaoamaral ,

You have to set flipTextureV property  of ARModel's obj variable to true 

for example: models[0].obj->flipTextureV = true; 

this will solve your problem of inverted texture.

dk00891

**Comment by ThorstenBux** [comment]
Answered
