### ISSUE TITLE
Need help creting dynamic marker

### ISSUE THREAD

**Issue by shashank2001** [artoolkit/artoolkit5#240]
I want to use web server to track the marker dynamically,i will be using nft feature so i will have image dataset on my server but is that possible that it can detect targets searching the server in mobile without giving any details ?

**Comment by Neuroforge** [comment]
It is possible. When ARToolkit 6 is released you will be able to load image dynamically.

However, if you want to do the entire image matching on a server you will need a custom image server.

I have created a web server based on this code..... it is possible to wrap it with either C# or Python.

https://github.com/dorian3d/DBoW2

**Comment by ThorstenBux** [comment]
No reply within 14days -> closing
