### ISSUE TITLE
How can I Load .obj file of model in nftBookProj

### ISSUE THREAD

**Issue by darshanpopat** [artoolkit/artoolkit5#241]
Hello,

I am developing an application in which I need to **load .obj** file in **nftBookProj** example.
Because when I convert **.obj** file of my model to **.osg** file format using **osgconv** command, it load my model too much big and without any color. So now I need to load .obj file in example.
If it is possible then please let me know the steps how I can make it done.
Or you can tell me that how I can convert **.obj** file to **.osg** file to get the same output model.

Waiting for your response.
Thanks in Advance.

**Comment by amalcao** [comment]
Which platform do you use? 
- For PC, you should make sure the obj file plugin for OSG is installed. 
- If you using android, the obj plugin should be linked into your native library statically, to do this, you should update the original osgPlugins.h ( located in artoolkit5/AndroidStudioProjects/nftBookProj/nftBook/src/main/jni/), uncomment the line `//USE_OSGPLUGIN(obj)`, and then rebuid the jni library by running the shell scripts in artoolkit/android/ .
- I have no iOS devices to test the iOS version.

By the way, if you just want to scale the size of the model, why not change the default setting in
objects.dat? And if your model with some texture, make sure the texture file is copied into your asset directory and the image type is supported by OSG.

Good luck!

**Comment by ThorstenBux** [comment]
Closing because solution was offered and no response since then. Feel free to open again if needed.
