### ISSUE TITLE
/artoolkit5-5.3.2/lib/SRC/VideoQuickTime7/QTKitVideo.h:41:9: 'QTKit/QTKit.h' file not found

### ISSUE THREAD

**Issue by Tommy-Leedian** [artoolkit/artoolkit5#242]
I met an issue when I tried to compile ARToolKit5 sample code. Details as below:
**IDE** Xcode 8.2
**OS** macOS Sierra 10.12.2
**Target** simpleLite
**Issue Info**
/artoolkit5-5.3.2/lib/SRC/VideoQuickTime7/QTKitVideo.h:41:9: 'QTKit/QTKit.h' file not found

![07f0004d-1bd2-4bdd-a7a6-5cec683dd50d](https://cloud.githubusercontent.com/assets/20126042/21892316/3177f7b4-d911-11e6-9e5e-4e298d87330b.png)

**Comment by amalcao** [comment]
The QTKit is removed from the xcode on 10.12 which causes this issue.
To fix it, you could download the macOS 10.11 SDK and replace the default one (for macOS 10.12) when building the artoolkit.
The SDK can be found [here](https://github.com/phracker/MacOSX-SDKs/releases/tag/MacOSX10.11.sdk).
Download and copy it to the sdk location of your xcode (maybe /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/ ),
open xcode, update the BaseSDK to 10.11, and then build the project.
You can find the detail [here](https://forum.openframeworks.cc/t/macos-10-12-sierra-xcode-8-quicktime-deprecation-workaround/24179/2).

**Comment by Tommy-Leedian** [comment]
Hi amalcao. It works for me now. TKS!
