### ISSUE TITLE
How can I define  nft markerID in Armovie project

### ISSUE THREAD

**Issue by ahmetoguzer** [artoolkit/artoolkit5#243]
Hi,I'm working on the armovie project but playing the same video for all markers.I need different video playback for different markers I should see nft MarkerID for this I would appreciate if you help
Thanks

**Comment by ThorstenBux** [comment]
Hi,
can you please tell me the platform you are targeting and what exactly you would like to achieve?

That would help me supporting you better.

**Comment by ThorstenBux** [comment]
No reply within 14days -> closing
