### ISSUE TITLE
Last character of logging message not showing on Win32

### ISSUE THREAD

**Issue by qian256** [artoolkit/artoolkit5#244]
Hi,
When I use arunity5 on windows platform, I found that the last character of debugging message is not showing. The behavior is like this:
`ARController (native): [info]ARController::startRunning(): called, start runnin`
I found out that the problem happens in the wrapper.

In line 1499 of `artoolkit5/lib/SRC/ARWrapper/ARController.cpp`, which is:
```c
vsnprintf(*bufPtr, *lenPtr, format, args);
```
should be changed to:
```c
vsnprintf(*bufPtr, *lenPtr + 1, format, args);
```

Explanation:
According to [http://www.cplusplus.com/reference/cstdio/vsnprintf/](http://www.cplusplus.com/reference/cstdio/vsnprintf/), actually at most n-1 bytes are copied to the destination buffer, and the last byte is assigned to null directly. Line 1500 is actually not necessary, but here we have to copy one more character. ;)

**Comment by BoiseBaked** [comment]
Thanks, fix on master.
