### ISSUE TITLE
Manually change the video resolution for tracking

### ISSUE THREAD

**Issue by xumengwei** [artoolkit/artoolkit5#248]
I want to decrease the resolution for quicker processing of tracking markers, while keeping the high resolution for display. I'm experimenting in ARNativeProj, but failed to do so. More specifically, I created another buffer which stores the compressed video image when nativeVideoFrame is called, and passed it to func arDetectMarker. But the output on my device looks quite strange.

Is there anybody helping me?

**Comment by Neuroforge** [comment]
Hello,

This is currently not supported.

If is possible that you could scale the input image.

https://artoolkit.org/blog/2016/05/opencv-with-artoolkit

Regards,

Daniel
