### ISSUE TITLE
ARToolkit for Android not working (not even any example including Codex Interactivus) after activity is switched off with BACK or HOME Button.

### ISSUE THREAD

**Issue by VladVuk** [artoolkit/artoolkit5#25]
I have problem with every ARToolkit application / example on any android phone I tried so far.

After I press BACK BUTTON or HOME button on the phone with started ARToolkit activity ( regardless if it is ARMovie, nftSimple, ARNativeOSG or even Codex Interctivus ) mostly always when I start that activity again it seems that it works but the AR marker recognition never happens anymore.

If I put : "android.os.Process.killProcess(android.os.Process.myPid());" - in OnDestroy() function then the whole application is killed and recognition works again. But that is not a solution.
Seeing it I assume that there is something in Native code which is not completely destroyed when activity die.

Can you help, provide advice, hint, support or example how to use multi session marker recognition in interactive switch on/off of some activity ?

Which part of Native code could make such issue ?

Regards,
Vlad

**Comment by dk00891** [comment]
hi, 

Facing same problem,

Vladvuk have you find any solution??

regards,
DK

**Comment by VladVuk** [comment]
Yes I found the issue and solved the problem.

Issue comes from the fact that each time when AR activity is started marker indexing is continuous which mean that marker index is increased by number of markers. For example if you have total number of 2 markers then by each start of AR activity your markers will get following indexes per iteration: 0,1   2,3   4,5 etc. 
And in your markers.dat index of marker is fix: 1,2 (actually 0,1).

You can solve it on two ways:
a) reset general counter - it is deep in artoolikit
or 
b) take care about reindexing marker numbers in markers.dat or whenever your AR activity use markers. and reset markers numbers to start with 1 whenever the application is restarted.

**Comment by hienbx94** [comment]
@VladVuk , Can you share code of Codex Interctivus?
I didn't found it on repository github.

**Comment by dk00891** [comment]
@VladVuk,

Sequence of actions to regenerate the issue:

1. start ARMovie application ->  NFT marker detected correctly, 
2. now click camera settings from menu of app -> camera setting will be shown
3. press back from camera settings  -> ARMovieactivity will start again and all marker data will be loaded again, but **after reloading marker data, Marker detection may work or may not work**.

I have checked logs while marker is getting loaded. it is always assigning page No.(index No.) starting from "0".

Are you having same problem as stated above??

regards,
DK

**Comment by dk00891** [comment]
hi all,

I found the solution.

in nativestop method, one has reset the detectedpage variable to -2, to restart tracking thread after switching application on/off state.

regards,
DK

**Comment by philip-lamb** [comment]
Fixed in https://github.com/artoolkit/artoolkit5/commit/df275b8f155ecf7bf021459044ac59ddb0628c24
