### ISSUE TITLE
how to generate "FeatureSet" from Camera Stream?

### ISSUE THREAD

**Issue by Mehdi-saber** [artoolkit/artoolkit5#250]
i want to generate FeatureSet or something like that from camera stream(android native) and send it to server then compare with nft markers that stores in server then send specific marker files to client...(something like cloud recognition)
any points?

**Comment by ThorstenBux** [comment]
Hi,

we cover issues and bug here. For such general questions please go to the forum at
http://artoolkit.org/community/forums/
