### ISSUE TITLE
Get particle systems working with ARToolKit?

### ISSUE THREAD

**Issue by KevinWSteele** [artoolkit/artoolkit5#252]
Hi, I'm working with ARAppOSG. I want to be able to use particle systems.

I found an example called cessnafire.osg: https://github.com/openscenegraph/OpenSceneGraph-Data/blob/master/cessnafire.osg
When I use osgviewer from the terminal, I can see the fire from the plane. However, when I put the cessnafire.osg file into the XCode project for ARAppOSG, I don't see the fire or the smoke when I run the app on my iPhone. 

I just see the plane - no particle systems.

How can I get the fire/smoke to appear?

**Comment by amalcao** [comment]
I have found solutions to fix the particle system BUG for the OSX and android version, see #237 for details. The iOS version is not tested since I have no license to run artoolkit on iOS devices. 
From my pint of view, this BUG happens because some OpenGL states are not initialized properly before rendering each frame of OSG scene.

**Comment by KevinWSteele** [comment]
Amal, thanks for answering, but I'm still have trouble getting it to work. 

I had seen that you had written In file simpleOSG.cpp as below just before calling the VirtualEnvironmentHandleARViewDrawPreCamera() :

   glEnableClientState(GL_VERTEX_ARRAY);
   glEnableClientState(GL_TEXTURE_COORD_ARRAY);

However, I am using ARAppOSG, which does not have that simpleOSG.cpp file. I have tried putting those two lines into ARViewController.m (in various places) and in ARView.m (in various places), but the fire never appeared.

I'll continue experimenting and post an update if I figure out the answer. If anyone has any other suggestions,  please let me know.

**Comment by amalcao** [comment]
Hi, I've found the reason, the plugins to load particle system are not statically linked to the app,
so all the OSG nodes from osgParticle library will not be loaded during rendering.
To fix this, just update the header file `examples/ARAppCore/osgPlugins.h` as below:
```
//
// osgPlugins.h
//
// This file is required when using a statically-linked version of OSG.
// It defines the graphics window implementation, the wrappers to use
// to load various OpenSceneGraph entities, and the plugins which should
// be loaded statically.
//
// To make use of osgPlugins.h, include it in your project, and link against
// the used OpenSceneGraph libraries and plugins.
//

#pragma once 

#include <osgViewer/GraphicsWindow>
#include <osgDB/Registry>

//windowing system
#if defined(__APPLE__)
USE_GRAPICSWINDOW_IMPLEMENTATION(IOS)
#else
#USE_GRAPICSWINDOW_IMPLEMENTATION(NONE)
#endif 

//plugins

USE_DOTOSGWRAPPER_LIBRARY(osg)
USE_DOTOSGWRAPPER_LIBRARY(osgParticle)
USE_DOTOSGWRAPPER_LIBRARY(osgFX)
USE_DOTOSGWRAPPER_LIBRARY(osgTerrain)
USE_DOTOSGWRAPPER_LIBRARY(osgText)
USE_DOTOSGWRAPPER_LIBRARY(osgVolume)
USE_DOTOSGWRAPPER_LIBRARY(osgSim)
USE_DOTOSGWRAPPER_LIBRARY(osgShadow)

USE_SERIALIZER_WRAPPER_LIBRARY(osg)
USE_SERIALIZER_WRAPPER_LIBRARY(osgAnimation)
USE_SERIALIZER_WRAPPER_LIBRARY(osgParticle)
USE_SERIALIZER_WRAPPER_LIBRARY(osgFX)
USE_SERIALIZER_WRAPPER_LIBRARY(osgTerrain)
USE_SERIALIZER_WRAPPER_LIBRARY(osgText)
USE_SERIALIZER_WRAPPER_LIBRARY(osgVolume)
USE_SERIALIZER_WRAPPER_LIBRARY(osgSim)
USE_SERIALIZER_WRAPPER_LIBRARY(osgShadow)

USE_OSGPLUGIN(osg)
USE_OSGPLUGIN(ive)
//USE_OSGPLUGIN(freetype)
//USE_OSGPLUGIN(obj)
//USE_OSGPLUGIN(gz)
//USE_OSGPLUGIN(zip)
#ifdef __APPLE__
USE_OSGPLUGIN(imageio)
#else
USE_OSGPLUGIN(jpeg)
USE_OSGPLUGIN(png)
USE_OSGPLUGIN(bmp)
USE_OSGPLUGIN(tga)
USE_OSGPLUGIN(rgb)
//USE_OSGPLUGIN(tiff)
//USE_OSGPLUGIN(gif)
#endif
```

In order to make it works, I add all plugins provided by OSG, note **some of them are not necessary for particle system**.
After doing that, the fire and smoke in model `cessnafire.osg` present, but the textures of the particle systems may not be loaded properly. I'm trying to find the solution to fix this new BUG.

**Comment by KevinWSteele** [comment]
Thank you so much for that advice. I followed it and I did manage to get fire-ish stuff appearing. 
However, the fire effect doesn't look that nice. It looks like several little yellow dots floating around instead of the slightly more realistic fire I get when just using osgviewer.

I'm also getting the following error message in XCode:

"Warning: ParticleEffect::setUpGeometries(..) not fully implemented."

And then, while running the app, the following lines appear on XCode whenever the fire should appear on screen:

"Warning: ParticleSystem::drawImplementation(..) not fully implemented.
Warning: ParticleSystem::drawImplementation(..) not fully implemented.
Warning: detected OpenGL error 'invalid enumerant' at after RenderBin::draw(..)"

Sorry for all the questions, but does anyone know of any way to get the fire to look better and/or fix those error messages?

Below, are two images - you can see that the fire looks quite a bit worse while running the app.

<img width="761" alt="screen shot 2017-02-10 at 8 12 28 pm" src="https://cloud.githubusercontent.com/assets/11259273/22849721/c351aaae-efcd-11e6-8310-34293d7576b7.png">
![img_5653](https://cloud.githubusercontent.com/assets/11259273/22849722/c361db40-efcd-11e6-954f-0268d342cf0b.jpg)

**Comment by amalcao** [comment]
The particle systems inside the cessnafire **can't be scaled up**, so you should make sure that the scale factors in file objects.dat are all 1, however, that will make your model too small on screen, update the size parameter in file marks.dat from 80.0 to 8.0 maybe a tricky way to fix that.
Or you can google how to make a scaleable osg particle system, to make a new model by yourself!

**Comment by KevinWSteele** [comment]
Thanks a lot, Amal - I really appreciate your help!

The fire definitely looks a lot better with the scale factors all at 1 and changing the 80.0 to 8.0 in markers.dat did seem to work pretty well too.
