### ISSUE TITLE
how to get marker id in ntfsimple android

### ISSUE THREAD

**Issue by bilal4922** [artoolkit/artoolkit5#253]
i want to get marker id from ntfsimple android

**Comment by ThorstenBux** [comment]
Hi, can you please go a bit more into detail what you would like to do? NFTSimple is an example on how to use ARToolKit on Android using C/C++ with the Android NDK. Do you need to do that or would you be fine to run on Android directly?

**Comment by ThorstenBux** [comment]
No reply within 14days -> closing
