### ISSUE TITLE
how to get nft marker size?

### ISSUE THREAD

**Issue by Mehdi-saber** [artoolkit/artoolkit5#254]
hi 
i want to cover marker(nft) by render video on it in a project based on ARMovie project(android native sample).
how to get marker size and set for content?
i changed code like below in ARMovie.cpp:nativeDrawFrame fucntion but video size changed to zero!
```
/*float w = 80.0f;
float h = w * (float)movieHeight/(float)movieWidth;*/
float w = markersNFT[i].marker_width;
float h = markersNFT[i].marker_height;
```
it's emergency!please help!

**Comment by amalcao** [comment]
Hi, @Mehdi-saber, I found a solution from the forums [here](http://artoolkit.org/community/forums/viewtopic.php?f=24&t=27202#p33253), it may solve your problem.

**Comment by Neuroforge** [comment]
Please see the original post here....

https://artoolkit.org/documentation/doku.php?id=3_Marker_Training:marker_nft_training
