### ISSUE TITLE
Can't read textures in ARAppNFT example

### ISSUE THREAD

**Issue by dizialina** [artoolkit/artoolkit5#256]
Hello! I have one problem with loading my 3D model. It doesn't appear on screen because it can't load textures.

This is log:
```
ReadTex(): Can't open file '/var/containers/Bundle/Application/94AC0AB2-9E88-467B-8D6C-ED071C2CC5DD/SwiftAR.app/Data2/models/textures/boddy-diffuse-dark-PINK.jpg ' for reading.
No such file or directory
EdenSurfacesTextureLoad(): Unable to read file '/var/containers/Bundle/Application/94AC0AB2-9E88-467B-8D6C-ED071C2CC5DD/SwiftAR.app/Data2/models/textures/boddy-diffuse-dark-PINK.jpg
'.
glmDrawArrays(): Error loading texture.
```

But jpg file exists in this directory. Tried to clean build folder, delete app, remove and add again Data2 folder in Build phases in Copy Bundle Resources, delete derived data, but nothing helped. Maybe someone had the same problem?

**Comment by tom-wei** [comment]
That also happened to me in Android.I can not figure out!This is my error:
`02-17 09:09:24.737 12711-12986/org.artoolkit.ar.samples.ARSimpleNativeCars E/libeden: ReadTex(): Can't open file 'Data/models/solid/Basketweave.jpg' for reading.
02-17 09:09:24.737 12711-12986/org.artoolkit.ar.samples.ARSimpleNativeCars E/libeden: No such file or directory
02-17 09:09:24.737 12711-12986/org.artoolkit.ar.samples.ARSimpleNativeCars E/libeden: EdenSurfacesTextureLoad(): Unable to read file 'Data/models/solid/Basketweave.jpg'.
02-17 09:09:24.737 12711-12986/org.artoolkit.ar.samples.ARSimpleNativeCars E/libeden: EdenSurfacesTextureLoad() couldn't read texture file "Data/models/solid/Basketweave.jpg".
02-17 09:09:24.737 12711-12986/org.artoolkit.ar.samples.ARSimpleNativeCars E/libeden: glmDrawArrays(): Error loading texture.`

**Comment by amalcao** [comment]
Make sure your `.obj` or `.mtl` files **DO NOT** use the Windows-style line endings `'\r\n'`, which is used by some free 3D models downloaded from the internet. If so, just convert them to Unix-style, [this](http://stackoverflow.com/questions/6373888/converting-newline-formatting-from-mac-to-windows) will help you to do the conversion. 
I hope this will help you, good luck!

**Comment by tom-wei** [comment]
@amalcao You save my day!谢谢你

**Comment by dizialina** [comment]
@amalcao  Yes, now it works. Thank you very much :)
