### ISSUE TITLE
importing MTL + OBJ files correctly?

### ISSUE THREAD

**Issue by KevinWSteele** [artoolkit/artoolkit5#257]
I downloaded a 3D model, opened it in Maya, and I then applied a texture. I then tried to use the model with my ARToolKit project and the texture didn't load well.

 The object looks well covered by the texture in Maya:
<img width="303" alt="screen shot 2017-02-18 at 6 31 10 pm" src="https://cloud.githubusercontent.com/assets/11259273/23097707/ea64c50e-f608-11e6-8a7a-6a29598a5053.png">

Then, I exported the model from Maya with the obj exporter. I added the obj, mtl, and jpg texture file to my AR iOS project. However, when I run the app, the model is not covered with the texture:
![img_5658](https://cloud.githubusercontent.com/assets/11259273/23097719/3f0f8a3a-f609-11e6-8a6c-2d1bc1352c1d.jpg)

This is what is in my mtl file:
newmtl lambert2SG
illum 4
Kd 0.00 0.00 0.00
Ka 0.00 0.00 0.00
Tf 1.00 1.00 1.00
map_Kd TexturesCom_MetalBare0104_1_M.jpg
Ni 1.00

Any ideas how to fix this problem so the texture covers the object?

**Comment by ThorstenBux** [comment]
Have a look at that and tell me if that solves it for you:
Change line 108 in ARWrapperNativeCarsExample to this:
obj = glmReadOBJ3(model0file, 0, 0,true); // context 0, don't read textures yet.

Then the texture mapping is fixed
Documentation for this method is here: https://github.com/artoolkit/artoolkit5/blob/master/include/Eden/glm.h#L386

Let me know if that helps.

**Comment by KevinWSteele** [comment]
Thanks, but that does not seems to have worked...

I am working with ARAppOSG. I wasn't sure where to put in that line you suggested, but I searched my project for glmReadOBJ3 and I found that function call in VEObjectOBJ.m.

I changed line 91: glmModel = glmReadOBJ3([file UTF8String], 0, FALSE, flipV) to glmModel = glmReadOBJ3([file UTF8String], 0, 0, true), but it did not work. It does look like that "don't read texture attribute" was already set to false....The texture still does not cover the object completely when I run the app on my phone...

**Comment by ThorstenBux** [comment]
Oh, sorry. I was in the Android world

**Comment by InheritX** [comment]
I have added .obj file which works fine in maya, blender and xcode preview mode but when i  run my app in my iPhone UVmapping is not correct. please help.

**Comment by amalcao** [comment]
If you using the openscenegraph to render the obj models, please make sure the bug is not caused by OSG. To verify that, you can install the OSG on your PC or mac, and run osgviewer to load your buggy obj files, if they cannot be rendered properly either, you'd better ask the community of OSG for help.

**Comment by KevinWSteele** [comment]
Thanks for the suggestion, Amal. However, I just ran osgviewer with my object and my object looks fine  and covered with the texture in osgviewer so I suppose the problem is not with OSG....

**Comment by amalcao** [comment]
Have you tried converting the .obj files to .OSG files by osgconvertor and load the OSG models instead?

**Comment by KevinWSteele** [comment]
Thanks again Amal! You're so helpful :) I used osgconv to convert my obj file to osg and now the object does look covered when I run my app.

It might be interesting if someone knows why the obj file doesn't work with ARToolKit...I'll plan to close this issue soon, but I'll leave it open for a little bit.
