### ISSUE TITLE
Modifying AssetHelper.class to recache the asset folder in app cache at runtime

### ISSUE THREAD

**Issue by Kartik-RTP** [artoolkit/artoolkit5#261]
This has to do with dynamically adding NFT markers

**Comment by Neuroforge** [comment]
Hello,

Are there any associated error messages?

Can you tell me your steps to reproduce this error.

Thanks.

**Comment by Kartik-RTP** [comment]
Hi there ! This is not a bug , rather its an enhancement. Right now , the application loads the assets at start and then they are used  . I want to change the assets during application runtime for which somebody suggested on the ["Dynamically add Markers (nft images) from server" ](https://artoolkit.org/community/forums/viewtopic.php?f=26&t=16057) discussion thread that for this one needs to modify AssetHelper.class    
I am yet to start on it  . If something meaningful occurs , I will share it. But in any case I created an issue for it .

**Comment by Neuroforge** [comment]
A word of warning, this is handled in ARToolkit6 very very well. So in perhaps a few weeks, you should switch to the new toolkit for this purpose.

**Comment by Kartik-RTP** [comment]
how long would it take for it to release ?  Please be specific as I have to
answer my higher ups about it as to why I will be scheduling this task to a
later date and how much delay do I want ? Will it be released within 2
weeks or so?

Regards

Kartik Gupta
4th year , CSE Department
IIT Ropar

**Comment by Neuroforge** [comment]
Unfortunately, i am not able to say how long it will take to be released and cannot guarantee it'll be within two weeks.

Alternatively, you could try to get onto the Early Access Program for ARToolkit6.

Please contact this email regarding the EAP, with details of your intended use and some background information about yourself.
philip.lamb@daqri.com

**Comment by Kartik-RTP** [comment]
@Neuroforge  I tried contacting Philip through the mail that you have provided but he hasn't replied . If possible , please help out . I have started looking at the code of artoolkit v5 , but with my current expertise , it seems a tough task.

**Comment by Neuroforge** [comment]
Hello,

I would like to help if i can, but this is a large task.  If you could pre-train your markers on a Web Server or something then the fset and iset would be available to add.

Your problem is the overhead of processing when creating the iset and fset. If you can find time to pre-process this, it will make your issue that much easier.

Regards,

Daniel

**Comment by Kartik-RTP** [comment]
Yes , I have already decided to do that (although it takes a lot of time ) but how do I dynamically load fset and iset files ,and also there is the requirement of incrementing the version number . What  should be  the process here ?

**Comment by Neuroforge** [comment]
Well, once you've downloaded the iset and fset you need to put them into the data folder where other assets are kept.

Then call markerID = ARToolKit.getInstance().addMarker("nft;Data/pinball");.

As for version number, i am unsure what this is in reference to.

**Comment by Kartik-RTP** [comment]
@Neuroforge  : Can I use java wrapper to deal with nft markers ? The example nftSimple uses the native libraries

**Comment by Kartik-RTP** [comment]
@Neuroforge Hi , I wanted to ask you where do I have to put the new marker files into ...you said that where the already existing files are ...but they are in assets folder and assets folder is read only at runtime in android ....I looked further that AssetHelper caches these files or folders , so Do i need to put those stuff in cacheDir ??
