### ISSUE TITLE
How to generate  libARWrapper.so

### ISSUE THREAD

**Issue by yxwandroid** [artoolkit/artoolkit5#266]
I  Run  ARSimpleNativeProj     

At the command line  input   ndk-build 
There is an error message
ARSimpleNativeCarsProj/aRSimpleNativeCars/src/main/jni/../../../../../../android/libs/armeabi/libARWrapper.so exists  or that its path is correct   

How to generate  libARWrapper.so
Thank you for

**Comment by ThorstenBux** [comment]
Please go through the documentation here:
http://artoolkit.org/documentation/doku.php?id=4_Android:android_native
