### ISSUE TITLE
Problem Running nftSimple

### ISSUE THREAD

**Issue by motenrique** [artoolkit/artoolkit5#270]
Recently I´ve compiled and run the nftSimple example in Visual Studio 2013 and all worked perfectly. Nevertheless, I tried to create a new project outside the SDK folder. I've linked the following libraries to my project (They are the same for the nftSimple project in SDK):

ARd.lib
ARICPd.lib
ARgsub_lited.lib
ARvideod.lib
AR2d.lib
pthreadVC2.lib
KPMd.lib
ARUtild.lib
libjpeg.lib

I have created the same files of the nftSimple project just to try it, but I have a problem when I run the .exe file: when the project run, it shows the messages in command line, but it's stopped at the next line: **_Start tracking thread_**. The programm shows the camera output image, but it doesn't make the tracking operations. Any error message isn't showed, but no tracking operations are done.

I don't know what could be the problem.

Thank you

**Comment by Neuroforge** [comment]
Are you able to debug the code and 'step through' it?

Regards

**Comment by ThorstenBux** [comment]
No reply within 14days -> closing
