### ISSUE TITLE
Take photo, screenshot, or recording of AR view?

### ISSUE THREAD

**Issue by KevinWSteele** [artoolkit/artoolkit5#271]
How can I write code (Objective-C) to capture the current camera view when running ARToolKIT and save it?

I am using ARAppOSG.  I would like to be able to add code to take a photo or a recording of the view with the augmented reality so that someone can save it to their iPhone's photo album.

However, when I try to take a photo of the view in ARViewController.m, I just get the Iris image, not the actual camera view  that was being displayed.

Does anyone have any suggestions? I think I had seen an article somewhere about how to take HD photos with ARToolKit using code, but I cannot find it now. Thanks!

**Comment by ThorstenBux** [comment]
Hi,

as this is not a main feature of the ARToolKit framework I suggest that you ask this question in our forum at artoolkit.org/community/forums/

ARToolKit's purpose is to provide you with image recognition and tracking functionality.

**Comment by KevinWSteele** [comment]
ok, thanks.
