### ISSUE TITLE
change my camera resolution from 640x480 to 1280x720 it stops the detection.

### ISSUE THREAD

**Issue by Macile** [artoolkit/artoolkit5#274]
HI all
Mobile phone can not be displayed  modle when the resolution  is 16:9，but when 4:3 or other it is right.
I donnot know why。
I used NFT。
Ideas and tips please

Regards

Max 

very thanks

**Comment by amalcao** [comment]
I've tested the resolutions with the aspect 16:9, both 1920x1080 and 1280x720 work for me, but when the resolution is set to 1920x1080, the time for detection is a little longer for my nexus7 (2013, wifi).
Make sure the correct camera param file is downloaded for the resolution you set, it will be downloaded automatically by the nftBookNative app and you can see the info from the android logcat monitor.

**Comment by Neuroforge** [comment]
Hello Max,

Changing the resolution will change the required lens model of the camera.

You need to have a calibration ready for each resolution to be used.

**Comment by ThorstenBux** [comment]
Yes @Neuroforge is probably right. Other than that you can try the forum for that question:
https://artoolkit.org/community/forums/
