### ISSUE TITLE
github source has not libARWrapper.so

### ISSUE THREAD

**Issue by kky0402** [artoolkit/artoolkit5#275]
(sorry about my english)

Hi,
I took github source because you said that like below link.
-> https://github.com/artoolkit/artoolkit5/issues/146

but github source had not libARWrapper.so file.
So, How can I make this file? building source?

Please give me something to solved this problem, Thanks

**Comment by ThorstenBux** [comment]
I guess what you need is to follow this documentation:

http://artoolkit.org/documentation/doku.php?id=4_Android:android_native <http://artoolkit.org/documentation/doku.php?id=4_Android:android_native>


—





Thorsten Bux | Developer Advocate
thorsten.bux_c@daqri.com <mailto:thorsten.bux_c@daqri.com>




www.artoolkit.org
