### ISSUE TITLE
Shadow Generation

### ISSUE THREAD

**Issue by AiNi-KuangBiao** [artoolkit/artoolkit5#278]
Can anyone tell me  how to make shadows for osg 3D models in artoolkit?
Many thanks.

**Comment by Neuroforge** [comment]
There's a great tutorial for OSG and shadows that can be downloaded here....

http://vr.port.ac.uk/resources/OSG_2_Shadows.pdf

**Comment by AiNi-KuangBiao** [comment]
@Neuroforge Thank you very much :).
