### ISSUE TITLE
 bone animation in ARToolkit can,t show normal?

### ISSUE THREAD

**Issue by AiNi-KuangBiao** [artoolkit/artoolkit5#280]
Hello,
when i load the osg model with  bone animation, it show nothing,but I find it have played the animation,when i use std::cout ,it print the animation name.How can i show the animation osg model.
Sorry for my poor English.

**Comment by amalcao** [comment]
Hi KuangBiao,

To get the bone animation work, you should make some update to the [arosg.cpp](https://github.com/artoolkit/artoolkit5/blob/master/lib/SRC/ARosg/arosg.cpp).
I think the best reference is the official example from OSG, you can find it here, [https://github.com/openscenegraph/OpenSceneGraph/tree/master/examples/osganimationviewer](https://github.com/openscenegraph/OpenSceneGraph/tree/master/examples/osganimationviewer)

Good Luck!

**Comment by AiNi-KuangBiao** [comment]
@amalcao ,
Thank you very munch for your prompt reply .
