### ISSUE TITLE
artoolkit build.sh error issue

### ISSUE THREAD

**Issue by kky0402** [artoolkit/artoolkit5#281]
hi,
I followed this link -> http://artoolkit.org/documentation/doku.php?id=4_Android:android_native
There was a problem compiling artoolkit to the latest version.
I have already set environment variables, and execute build.sh by git bash shell.
My notebook's OS is windows 10. and IDE is eclipse.

here is error log.

Building on Microsoft Wins10 Desktop (x86_64)
ARToolKit5 Android MK file (armeabi)
ARToolKit5 Android MK file (armeabi-v7a)
ARToolKit5 Android MK file (x86)
ARToolKit5 Android MK file (mips)
ARToolKit5 Android MK file (arm64-v8a)
ARToolKit5 Android MK file (x86_64)
ARToolKit5 Android MK file (mips64)
[armeabi] Install        : libc++_shared.so => libs/armeabi/libc++_shared.so
[armeabi-v7a] Install        : libc++_shared.so => libs/armeabi-v7a/libc++_shared.so
[x86] Install        : libc++_shared.so => libs/x86/libc++_shared.so
[mips] Install        : libc++_shared.so => libs/mips/libc++_shared.so
[arm64-v8a] Install        : libc++_shared.so => libs/arm64-v8a/libc++_shared.so
[x86_64] Compile        : arvideo <= videoLuma.c
[x86_64] Install        : libc++_shared.so => libs/x86_64/libc++_shared.so
[mips64] Compile        : ar <= arPattAttach.c
jni/../../lib/SRC/Video/videoLuma.c:129:88: error: use of undeclared identifier 'ANDROID_CPU_FAMILY_X86_64'; did you mean 'ANDROID_CPU_FAMILY_X86'?
                                     ((features & ANDROID_CPU_FAMILY_X86 || features & ANDROID_CPU_FAMILY_X86_64) && (features & ANDROID_CPU_X86_FEATURE_SSSE3))); // Can also test for: ANDROID_CPU_X86_FEATURE_POPCNT, ANDROID_CPU_X86_FEATURE_SSE4_1, ANDROID_CPU_X86_FEATURE_SSE4_2, ANDROID_CPU_X86_FEATURE_MOVBE.
                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                       ANDROID_CPU_FAMILY_X86
jni/../../include/android\cpu-features.h:39:5: note: 'ANDROID_CPU_FAMILY_X86' declared here
    ANDROID_CPU_FAMILY_X86,
    ^
[mips64] Compile        : ar <= arPattCreateHandle.c
1 error generated.
[mips64] Compile        : ar <= arPattGetID.c
make: *** [obj/local/x86_64/objs/arvideo/__/__/lib/SRC/Video/videoLuma.o] Error 1
make: *** Waiting for unfinished jobs....
[mips64] Compile        : ar <= arPattLoad.c
[mips64] Compile        : ar <= arPattSave.c
Exiting ndk-build script abnormally terminated.

Please tell me the solution. thanks.

**Comment by ThorstenBux** [comment]
Did you solve it? Or what is the status?

**Comment by kky0402** [comment]
I solved it. This issue is fixed.

**Comment by Neuroforge** [comment]
What was the solution?

**Comment by kky0402** [comment]
while copying source, i made a mistake. 
Just copy and paste github source to project source rightly.
