### ISSUE TITLE
OpenGL/gl.h file not found on macOS 10.12.4

### ISSUE THREAD

**Issue by tantanbei** [artoolkit/artoolkit5#287]
I want to compile the artoolkit source code by XCode. And download the macOS 10.11 SDK and replace the default one (for macOS 10.12) for fixing "QTKit/QTKit.h" can not found issue. But now, I met the **"OpenGL/gl.h"** file not found issue
**IDE** Xcode 8.3.1
**OS** macOS Sierra 10.12.4
**Target** simpleLite
<img width="347" alt="screen shot 2017-04-15 at 15 28 43" src="https://cloud.githubusercontent.com/assets/12421377/25061847/b3ffb266-21f1-11e7-9988-c0d9a674cbf8.png">

**Comment by Neuroforge** [comment]
Did you add the OpenGL Framework to your project?

Check the loaded Frameworks.

**Comment by tantanbei** [comment]
<img width="291" alt="screen shot 2017-04-18 at 22 24 30" src="https://cloud.githubusercontent.com/assets/12421377/25136589/087f4a02-2488-11e7-8cb7-172dbcbc3369.png">
<img width="845" alt="screen shot 2017-04-18 at 22 50 39" src="https://cloud.githubusercontent.com/assets/12421377/25137183/92e0f280-2489-11e7-9fdb-c7144db21c48.png">

This is my artoolkit project menu. I think I loaded the OpenGL Framework on my project

**Comment by amalcao** [comment]
Make sure the OpenGL framework is included in the SDK which you used to build the project.
If the SDK 10.11 is installed followed the comment for issue #242, you can find the OpenGL headers
in **/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/**.
Try to download the correct SDK from [here](https://github.com/phracker/MacOSX-SDKs/releases/tag/MacOSX10.11.sdk) and re-install it if the OpenGL headers are not found.

**Comment by tantanbei** [comment]
@Neuroforge @amalcao Thank you for your suggestion! This issue is caused by my uncompress software, it is wrong to extract the link file.

**Comment by hardikdarji** [comment]
you can define macro in build settings, if you doing for iOS platform only. 

CC_PLATFORM_IOS
