### ISSUE TITLE
Show Splash Screen when ARView and camera is staring.

### ISSUE THREAD

**Issue by VikasSinghaiAndroid** [artoolkit/artoolkit5#29]
Hi,

If i want to show splash screen when ARView and camera is staring once camera is up and running then hide splash screen, where I can show/hide splash screen in native ARToolkit sample project.

Regards,
Vikas

**Comment by ThorstenBux** [comment]
Hi @VikasSinghaiAndroid,

you may want to try asking the forum about that: http://artoolkit.org/community/forums/viewforum.php?f=26

I'm closing it here now as we mainly use GitHub to address bugs and issues.
