### ISSUE TITLE
Blackmagic capture in ARToolkit for Unity Windows

### ISSUE THREAD

**Issue by jhurlbut** [artoolkit/artoolkit5#297]
I am unable to get ARToolkit working with my BlackMagic UltraStudio 4k Extreme. When running calib_camera.exe I have tried a variety of vconf settings and all of them fail to correctly capture the frame. With most settings I get a black screen but I can see the input on the blackmagic device so I know it's capturing but it appears that ARToolkit is interpretting the frame buffer incorrectly. I am able to get it to work with setting the device to QUICKTIME but that is incompatible with Unity. I have tried using WinDS and WinMF with a variety of settings but nothing works.

**Comment by philip-lamb** [comment]
The QuicktTime module is unfortunately obsolete, and I don't know what kind of support for MediaFoundation is provided by the BlackMagic board. Alternately, if you can get a stream running in AMCAP, you should be able to get input via the DirectShow module.

**Comment by jhurlbut** [comment]
I was able to get it to work
