### ISSUE TITLE
[iOS][Http] - Play remote video above marker 

### ISSUE THREAD

**Issue by alessioarsuffi** [artoolkit/artoolkit5#303]
Hello everyone, thanks for this open source library!

I was trying to play a video from a remote URL in iOS when a marker is focused by camera. I'm receiving this error when creating AVAssetReader:

    Cannot initialize an instance of AVAssetReader with an asset at non-local URL 'https://www.w3schools.com/tags/mov_bbb.mp4'ù

and after this log app crashed at:

    CMSampleBufferRef sampleBuffer = [_videoTrackOutput copyNextSampleBuffer]; 

error is:

    [AVAssetReaderTrackOutput copyNextSampleBuffer] cannot copy next sample buffer before adding this output to an instance of AVAssetReader (using -addOutput:) and calling -startReading on that asset reader

i'm using a real device to test. Any suggestion will be really appreciated! thanks

**Comment by Infodreams** [comment]
Hi,

I'm experiencing the same issue while trying to play a remote video. I have modified the original code a bit:

ARAppCore/VirtualEnvironment.m (line: 242)
`       /* if (!arUtilGetDirectoryNameFromPath(objectFullpathC, objectDataFileFullpathC, sizeof(objectFullpathC), 1)) { // Get directory prefix.
            fclose(fp);
            return (objectsAdded);
        }*/
        strcpy(objectFullpathC, buf);
        //strncat(objectFullpathC, buf, sizeof(objectFullpathC) - strlen(objectFullpathC) - 1); // Add name of file to open.`

In this way, the application will not append the local assets folder name to the file name, and I'm able to specify urls directly inside the "models.dat" file.

Could anyone help me to fix this? Many thanks

**Comment by Neuroforge** [comment]
Hello,

Is this SO post of any use in resolving your issue?

http://stackoverflow.com/questions/6242131/using-avassetreader-to-read-stream-from-a-remote-asset

Regards,

Daniel

**Comment by alessioarsuffi** [comment]
Hello @Neuroforge,

thanks for your answer, unfortunately, that SO answer is not helping me. We cannot extract a CGImageRef from _assetImageGenerator, although Xcode is not giving us a message on what's the error.
