### ISSUE TITLE
aRSimple

### ISSUE THREAD

**Issue by Renannr** [artoolkit/artoolkit5#304]
Hello!

I would like to change a little bit the example of ARSimple.
How do I display an image? (.png or .jpeg) Instend of the cube

Thanks

**Comment by Neuroforge** [comment]
Hello Renannr,

Please see ARAppMovie. Although this plays a video file, it can be adapted to how an image.

https://github.com/artoolkit/artoolkit5/tree/master/examples/ARAppMovie

Regards,

Daniel

**Comment by Renannr** [comment]
Thanks! But... it's running in android either?
I'd like to develop an application for android with augmented reality. This app would show an image on top of a marker. Which example can help me with this?

Sorry for my english. I only understand Portuguese.

**Comment by Neuroforge** [comment]
The ARToolkit will give you marker detection and tracking. What you do with that result in your app is up to you.

The image has to be arranged based on this resulting rotation matrix.

Take the result, see how it's done in the ARAppMovie, and then apply those principles to your Android project.
