### ISSUE TITLE
How To make one marker give multiple object can be change?

### ISSUE THREAD

**Issue by amirfian** [artoolkit/artoolkit5#306]
in unity, i try with setactive object false/true. it can't change object

**Comment by Neuroforge** [comment]
Hello Amirfian,

You will need to add and remove the models programtically. You cannot add two and switch.

Kind regards,

Daniel

**Comment by amirfian** [comment]
Hmm. If that way, i must create many marker and many clone of object

**Comment by ThorstenBux** [comment]
I'm just thinking loud here. But isn't it possible to add two objects to one marker and make then visible/invisible on mouse click for example?

**Comment by Neuroforge** [comment]
Yeah, that could work as well. It would still require some programtic work to do the switching, but you're probably right!

**Comment by amirfian** [comment]
Yeah.. im thinking too, and try it. It can't be like that. It something
must change in code ArController. But i didn't know wheres to change. I'm
change little code any make broke the structure code.

**Comment by ThorstenBux** [comment]
I'm just trying that one will be back with the result

**Comment by ThorstenBux** [comment]
Works like a charm for me
`        
        GameObject.FindWithTag ("cube").transform.localScale = new Vector3(0.04f, 0.04f, 0.04f);
        GameObject.FindWithTag ("sphere").transform.localScale = new Vector3(0, 0, 0);
`

OR

`GameObject.FindWithTag ("Sphere").SetActive (false);`

But I couldn't figure out how to make it visible again as 'Find' only finds active GameObjects

**Comment by amirfian** [comment]
Thank you very much Sir ThorstenBux, it's really work it 👍 . but it's something in artoolkit can't do, when we want to use click or touch object. 

link click on camera : https://www.youtube.com/watch?v=OCGoTiV4kbM
