### ISSUE TITLE
Image recognition with artoolkit

### ISSUE THREAD

**Issue by rahulroxx** [artoolkit/artoolkit5#311]
I want to do recognize a book page and play a video in the video player like mx player. ( it is new activitiy or new intent ). 
Documentation doesn't clearly show how to do this. 
Please help me.

**Comment by Neuroforge** [comment]
Hello,

It depends on the platform you are using desktop, ios. android etc.

Please see https://github.com/artoolkit/artoolkit5/tree/master/examples/ARAppMovie for tips on how to do this with iOS.

Regards,

Daniel

**Comment by rahulroxx** [comment]
I want to perform it on android phone.

**Comment by Neuroforge** [comment]
The ARMovie app for Android is here....

https://github.com/artoolkit/artoolkit5/tree/master/AndroidStudioProjects/ARMovieProj

ARToolkit 6 will be much better at image recognition. 2-3 weeks, until Beta release. I can't talk about it, but it is much more suitable for you.

I think with ARToolkit it could give you the image ID. Then you'd need to pass that value to the player activity so it knows which video to play.

**Comment by rahulroxx** [comment]
Thanks a lot, :)  @Neuroforge. I have one book page ( it is a story telling book ). I want to play a video that is associated with that page on android video player ( not on ARCamera ). Can I use ARMovie for this task?.
If yes, What are the steps for generating model so that ARToolkit recognise the page and play video.
