### ISSUE TITLE
Undefined symbols for architecture arm64 in Xcode 8.2.1

### ISSUE THREAD

**Issue by akjesto** [artoolkit/artoolkit5#313]
I tried to this ARToolkit library to my new app.My application running on Xcode 8.2.1. I added this library files and some classes to my Xcode project.But I always got an error like the following.

**Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_ARMarkerNFT", referenced from:
      objc-class-ref in ARViewController.o
ld: symbol(s) not found for architecture arm64**

Please help me how to solve this issue in Xcode8.2.1.

**Comment by RakeshKoplodR** [comment]
Hi, I also had same issue. I resolved this by changing in "Build Setting". Please find the attachment where I did change.

<img width="865" alt="screen shot 2017-05-30 at 2 21 27 pm" src="https://cloud.githubusercontent.com/assets/12967064/26575570/6f901cea-4543-11e7-8313-ce483294ab2d.png">

**Comment by akjesto** [comment]
Hi Rakesh
What is these two values for macros WITH_NFT DEBUD=1 , WITH_NFT ? Could you explain about this?

**Comment by RakeshKoplodR** [comment]
Hi, I have googled about it and found this solution. In ARMarker.m you can find the code

#ifdef WITH_NFT
#  import "ARMarkerNFT.h"
#endif

I also don't know much about these macros.

Does this solve your problem?

**Comment by akjesto** [comment]
Hi Rakesh, Its working fine. Thank you so much.You are great.That issue fixed.
But now I am getting one error like **Unable to automatically determine camera parameters. Using default. unable to open camera parameters file "Data2/camera_para.dat" for reading.**

**Comment by RakeshKoplodR** [comment]
Try to add below code in Appdelegate:

arUtilChangeToResourcesDirectory(AR_UTIL_RESOURCES_DIRECTORY_BEHAVIOR_BEST, NULL);

**Comment by akjesto** [comment]
I already added this line in my appdelegate file.

**Comment by akjesto** [comment]
Hi Rakesh 
I fixed the issue like I added **Data2** folder to **copy bundle resources** to **Build phases** in app target.

Please also note that when we add **Data2** folder to our project choose **create folder references**(not select **create groups**). Please also go through the following image

![datanft](https://cloud.githubusercontent.com/assets/8862491/26622512/4ce58a34-4608-11e7-9d37-218b923500a1.png)
