### ISSUE TITLE
iOS ArToolkit with Swift

### ISSUE THREAD

**Issue by cihadhoruzoglu** [artoolkit/artoolkit5#316]
I have a XCode 8 project written with swift. I want to import artoolkit to my project but always I get a build error. Do you know any ArToolkit implemented with swift sample project?

**Comment by ThorstenBux** [comment]
Hi, unfortunately, we do not support Swift right now. Because of that, there is no example I can give you to make it work within a Swift project.

**Comment by leszek-s** [comment]
Here you can find an instruction on how to build artoolkit5 with basic functionality as a framework that can be included in a swift app:
https://stackoverflow.com/questions/39333823/ios-artoolkit-xcode-implementation/48338576#48338576
