### ISSUE TITLE
Keeping the scene even when target is lost

### ISSUE THREAD

**Issue by rahulroxx** [artoolkit/artoolkit5#317]
I am developing a puzzle game. I want square marker to get recognized and then play puzzle on that screen. I want to retain the puzzle even when target image is lost. I am developing puzzle game on unity.

**Comment by ThorstenBux** [comment]
In Unity3D we implemented an option to stay visible for a certain amount of time. You can have a look at the ARTrackedObject script the variables in question are visibleOrRemain and secondsToRemainVisible.
