### ISSUE TITLE
Does artoolkit support 3D object tracking?

### ISSUE THREAD

**Issue by skylook** [artoolkit/artoolkit5#32]
Good to have such a nice project of AR. But does it support 3D object tracking? I really need it.
Thanks :)

**Comment by philip-lamb** [comment]
Not at present. Thanks for your interest though.

**Comment by macarney** [comment]
skylook, did you ever find a solution for 3D object racking? I have a similar project and was curious what you've been able to come up with.

**Comment by skylook** [comment]
hi macarney, 

if you need an open-source or free AR SDKs that support 3d object tracking, I have no idea for now (hopefully artoolkit will support). Somehow, if you know much about SLAM & CV, it may be possible to develop your own sdk (ORB-SLAM may be a good one to start with).

If you mean commercial SDKs, I think Vuforia is a good one :)
