### ISSUE TITLE
lack of CONTRIBUTE.md file for guiding how to contribute?

### ISSUE THREAD

**Issue by Kartik-RTP** [artoolkit/artoolkit5#324]
Since its a open source project , it would be good if various naming conventions are given for developers to stick to..

**Comment by ThorstenBux** [comment]
@Kartik-RTP We have our coding guidelines here: https://archive.artoolkit.org/documentation/doku.php?id=9_Community:3-coding_guidelines

However, you are right a contribute.md file to link there would be good.
