### ISSUE TITLE
Getting Unable to start AR tracking Please check that you have a camera connected error

### ISSUE THREAD

**Issue by KaushikRay** [artoolkit/artoolkit5#328]
I am not sure which repo is correct place to log this bug -
Hello,

I have just started development in AR / VR category and using ARToolkit with Unity. I created the most simple AR tracker with hiro.
Whenever I run the projet it gets stuck at above title error - 

![error](https://user-images.githubusercontent.com/6602443/27899977-b1d26aa8-622c-11e7-8bb8-d7323079773d.png)

And this is the console details the errors ones - 

ARController (native): [error]ARWrapper::ARToolKitVideoSource::open2(): error-failed to load camera parameters camera_para.dat, calling close(), exiting returning false
UnityEngine.Debug:Log(Object)
ARController:Log(String) (at Assets/ARToolKit5-Unity/Scripts/ARController.cs:1656)
ARNativePlugin:arwStartRunningB(String, Byte[], Int32, Single, Single)
PluginFunctions:arwStartRunningB(String, Byte[], Int32, Single, Single) (at Assets/ARToolKit5-Unity/Scripts/PluginFunctions.cs:114)
ARController:StartAR() (at Assets/ARToolKit5-Unity/Scripts/ARController.cs:607)
ARController:Start() (at Assets/ARToolKit5-Unity/Scripts/ARController.cs:393)

ARController (native): [info]Closing ARToolKit video.
UnityEngine.Debug:Log(Object)
ARController:Log(String) (at Assets/ARToolKit5-Unity/Scripts/ARController.cs:1656)
ARNativePlugin:arwStartRunningB(String, Byte[], Int32, Single, Single)
PluginFunctions:arwStartRunningB(String, Byte[], Int32, Single, Single) (at Assets/ARToolKit5-Unity/Scripts/PluginFunctions.cs:114)
ARController:StartAR() (at Assets/ARToolKit5-Unity/Scripts/ARController.cs:607)
ARController:Start() (at Assets/ARToolKit5-Unity/Scripts/ARController.cs:393)

ARController (native): [error]ARController::startRunning(): Error: unable to open video source, exiting, returning false
UnityEngine.Debug:Log(Object)
ARController:Log(String) (at Assets/ARToolKit5-Unity/Scripts/ARController.cs:1656)
ARNativePlugin:arwStartRunningB(String, Byte[], Int32, Single, Single)
PluginFunctions:arwStartRunningB(String, Byte[], Int32, Single, Single) (at Assets/ARToolKit5-Unity/Scripts/PluginFunctions.cs:114)
ARController:StartAR() (at Assets/ARToolKit5-Unity/Scripts/ARController.cs:607)
ARController:Start() (at Assets/ARToolKit5-Unity/Scripts/ARController.cs:393)

ARController: Error starting running
UnityEngine.Debug:Log(Object)
ARController:Log(String) (at Assets/ARToolKit5-Unity/Scripts/ARController.cs:1656)
ARController:StartAR() (at Assets/ARToolKit5-Unity/Scripts/ARController.cs:616)
ARController:Start() (at Assets/ARToolKit5-Unity/Scripts/ARController.cs:393)

AROrigin: Found 1 markers eligible to become base marker.
UnityEngine.Debug:Log(Object)
ARController:Log(String) (at Assets/ARToolKit5-Unity/Scripts/ARController.cs:1656)
AROrigin:FindMarkers() (at Assets/ARToolKit5-Unity/Scripts/AROrigin.cs:110)
AROrigin:Start() (at Assets/ARToolKit5-Unity/Scripts/AROrigin.cs:116)

Looks like the code is not able to find camera_para.dat i find this in my AR folder not sure if this is correct?

![arfolder](https://user-images.githubusercontent.com/6602443/27900346-49e8b0c6-622e-11e7-9fb5-549a426f8fd7.png)

Can someone please help with same?
Thanks.!!

**Comment by ThorstenBux** [comment]
Please keep it here: https://github.com/artoolkit/arunity5/issues/174
