### ISSUE TITLE
open vs120\ARToolKit5.sln , always load project failed.

### ISSUE THREAD

**Issue by baesky** [artoolkit/artoolkit5#33]
OS:Win 10
IDE: VS 2013

**Comment by Neuroforge** [comment]
Can you provide more details? I am issues with Win 10 and VS2013, but i was able to load the project. Did you run the configure script?

Configure-win32.vbs

**Comment by baesky** [comment]
thanks, I have resolve it by this method: 
1) Please open Windows Explorer, and navigate to <Visual Studio Installation Path>\Common7\IDE (by default is <C:\Program Files \Microsoft Visual Studio 11.0\Common7\IDE>); 
2) Delete the ItemTemplatesCache, ProjectTemplatesCache folder; 
3) Open Visual Studio Command Prompt x64 Cross Tools Command Prompt under Start menu -> All Programs -> Microsoft Visual Studio 2012 -> Visual Studio Tools (run it with Administrator privilege: right-click the program -> Run as administrator); 
4) Run the devenv /InstallVSTemplates switch; 
5) Run the devenv /Setup switch

**Comment by baesky** [comment]
I had installed vs2013 and vs2015 on win10, It should due to my develop enviroment chaos :)

**Comment by Neuroforge** [comment]
Awesome. Can you please close this issue. :) Thank you.
