### ISSUE TITLE
Windows 7 + Android Studio + nftSimple build error?

### ISSUE THREAD

**Issue by raj19** [artoolkit/artoolkit5#330]
Hi, 
Trying to run nftsimple project in android studio with windows 7 environment not working.

For NFT: 
1. Setting up an environment variables is done
2. Installed git bash and trying to run build.sh and build_native_example.sh  throws error "Development platform not supported, exiting script*
3. Inside build.sh it is written as 
 #Checking for Windows in a non-cygwin dependent way.
    WinsOS=
    if [[ $OS ]]; then
        WinsVerNum=${OS##*-}
        if [[ $WinsVerNum = "10.0" || $WinsVerNum = "6.3" ]]; then
            if [[ $WinsVerNum = "10.0" ]]; then
                WinsOS="Wins10"
            else
                WinsOS="Wins8.1"
            fi
            echo Building on Microsoft ${WinsOS} Desktop \(${ARCH}\)
            export HOST_OS="windows"
            NDK_BUILD_SCRIPT_FILE_EXT=".cmd"
            CPUS=`/usr/bin/nproc`
        fi
    fi
fi

if [[ ! $CPUS ]]; then
    echo **Development platform not supported, exiting script**
    exit 1
fi

My windows version number is 6.1. It means windows 7 with nft for artoolkit is not supported?
Any inputs?

**Comment by ThorstenBux** [comment]
Yes we do not support Windows 7 anymore.
