### ISSUE TITLE
Building on Windows VS2013 - Quicktime Fail

### ISSUE THREAD

**Issue by Neuroforge** [artoolkit/artoolkit5#34]
Hello,

Building the ARToolkit in Visual Studio 2013 in Windows 10 produces these errors in videoQuickTime.c under the QuickTime folder for ArVideo.

Intellisense highlights as errors.
<pre><code>
....
#elif defined(_WIN32)
#  ifndef __MOVIES__
#    include <Movies.h>
#  endif
#  ifndef __QTML__
#    include <QTML.h>
#  endif
#  ifndef __GXMATH__
#    include <GXMath.h>
#  endif
#  ifndef __QUICKTIMECOMPONENTS__
#    include <QuickTimeComponents.h>
#  endif
#  ifndef __MEDIAHANDLERS__
#    include <MediaHandlers.h>
#  endif
#else
#  error
#endif
....
</code></pre>

These header files are part of the Quicktime SDK. How do you get these files to compile?

Stackoverflow: (http://stackoverflow.com/questions/6742 ... or-windows)
"Apple has mostly replaced QuickTime with other APIs that are not available on Windows such as QTKit."

What is the solution here?

**In my research, i have found the OpenFrameWorks (http://www.openframeworks.cc/) has these header files included. Perhaps we could change the VS2013 solution to be a OpenFrameworks Visual Studio Template.**

Regards,

Daniel

**Comment by mohghaderi** [comment]
1. Download and install QuickTime for windows: https://secure-appldnld.apple.com/quicktime/031-43075-20160107-c0844134-b3cd-11e5-b1c0-43ca8d551951/quicktimeinstaller.exe
2. Download QuickTime 7.3 SDK from Apple Developer (You will need apple developer account) https://developer.apple.com/downloads/: http://adcdownload.apple.com/QuickTime/quicktime_7.3_sdk_for_windows/quicktimesdk.zip
3. Run C:\Program Files (x86)\ARToolKit5\VisualStudio\vs120\Patch QuickTime 7.3 SDK\PatchQuickTime73SDK.vbs to configure for this version
