### ISSUE TITLE
https://omega.artoolworks.com/app/calib_camera/download.php is down!

### ISSUE THREAD

**Issue by eurbon** [artoolkit/artoolkit5#347]
AR Toolworks server at URL https://omega.artoolworks.com/app/calib_camera/download.php which provides the camera calibration data is inaccessible. Connection to the server times out on request.

By the way is there a way to run calibration file  locally if my app is not using internet?

**Comment by kngfrhzs** [comment]
Hello @eurbon , did you find a solution for this problem ?

**Comment by eurbon** [comment]
Had to recompile whole android ndk and then update my project with recent libraries which did not require connection to outside anymore.

**Comment by kngfrhzs** [comment]
Thanks a lot 👍

**Comment by VladVuk** [comment]
Can you explain more and send link to those recent libraries?


ned, 22. lis 2017. u 20:45 Eimantas Urbonas <notifications@github.com>
napisao je:

**Comment by eurbon** [comment]
Full guide here https://archive.artoolkit.org/documentation/doku.php?id=4_Android:android_native

Short guide:

Install android studo ide
Install ndk via android studio
Install gitbash as said in FULL GUIDE (above)
Download and extract files https://github.com/artoolkit/artoolkit5/
Change SetupEnvVars file path accordingly to paths and dont forget to input ANDROID_NDK_ROOT to Path as said in FULL GUIDE (above)
Launch SetupEnvVars

Finally, go to /artoolkit5-master/android  and run ./build.sh

Copy all new libs from/artoolkit5-master/android/libs on to your app

My SetupEnvVars is like this:

```
setx ANDROID_HOME C:/Users/EimantasUrbonas/AppData/Local/Android/sdk
setx ANDROID_NDK_ROOT C:/Users/EimantasUrbonas/AppData/Local/Android/sdk/ndk-bundle
setx NDK C:/Users/EimantasUrbonas/AppData/Local/Android/sdk/ndk-bundle
setx BOOST_LIB C:/Projects/ExternalLibs/boost_1_63_0
setx ARTOOLKIT5 C:/Users/EimantasUrbonas/Desktop/ARTOOLKIT-LIBRARY-BUILD
```

**Comment by leticiaporto** [comment]
Your libs work for me. Thank you!

**Comment by ley995** [comment]
@eurbon Link Dropbox was die. Can you re-upload your compiled libs. I am a newbie.

**Comment by tomascimadoro** [comment]
@eurbon Hi! Same here!! I am trying to compile the libraries but I get an error, can you upload yours please?

**Comment by eurbon** [comment]
Come on guys. I gave u full instructions and seems that everyone was too lazy to compile themselves/share. Don't expect everything on plate, not everyone is willing to invest hours of their time to give what u need. 

Anyways, updated the link: https://www.dropbox.com/s/tmfgusdmbodelyk/jniLibs.zip?dl=1

**Comment by deedoc** [comment]
Hi guys! I can feel your pain=)
Recently i deployed app on Google play and my app was rejected because of it used OpenSSL.

OpenSSL is used by curl which is used by ARToolkit's cparamSearch.c - module which downloads calibration parameters from artoolworks.com and stores them locally

I noped cparamSearch.c, throwed out curl, sqlite3 and nxjson. Size of my apk reduced from 17mb to 7mb Oo.

Here is prebuilt [libs.zip](https://github.com/artoolkit/artoolkit5/files/1590578/libs.zip) and my [artoolkit5-patch.zip](https://github.com/artoolkit/artoolkit5/files/1590583/artoolkit5-patch.zip) for 6323b0ca3fecb65184f3de854de4b85747894883 to get artoolkit built on my win7x64 via ndk-build.
Here is commands:
```
(inside artoolkit5/android folder)
  1. build artoolkit: ndk-build -j 4
  2. build artoolkit android wrapper: ndk-build -j 4 NDK_APPLICATION_MK=jni/Application-ARWrapper.mk
```

**Comment by 5y** [comment]
@deedoc  @eurbon Thank you for sharing your solutions.
I find out calibration is the reason of the very long black screen before the running.
Is there any solution for Unity SDK? Should I recompile the whole package then replace the lib on unity? Or is there any solution for put the default calibration and disable online checking?

**Comment by deedoc** [comment]
@5y, yes cParamSearch is reason of stuck before recognition starts.
Just use my noped version of cParamSearch.c and build artoolkit for your unity project.
Unfortunately i have no experience in building artoolkit for unity

**Comment by 5y** [comment]
@deedoc Thank you for the reply. I should find documents for building toolkit for unity and try your solution. However, I found several related lines here [1]. I hope to find a solution or even replace an offline version of calibration parameters.

1-  https://github.com/artoolkit/arunity5/blob/3e648c1ecd50486e692e949a81a17caf54bea0bb/src/Unity/Assets/ARToolKit5-Unity/Scripts/ARController.cs#L584

**Comment by deedoc** [comment]
@5y I think you cant avoid rebuilding artoolkit c part.
Code in ARController.cs looks like providing default calibration params, but artoolkit tries to load "better one" from artoolworks server. That is why i had to nope cParamSearch.c for my android project

**Comment by ThorstenBux** [comment]
Take a look at the artoolkitX fork https://github.com/artoolkitx/artoolkit5. We have setup a new calibration server and compiled the URLs into the new binaries. Downloadable binaries are here: http://www.artoolkitx.org/docs/downloads/

**Comment by 5y** [comment]
@deedoc Yes, Exactly. maybe I should try the same method here for calling the function in Unity.
Unfortunately, **I have lots of difficulties for using the ARtoolkit servers. even the new servers.In my country.**

@ThorstenBux  Thank you for sharing the links. However, I can't find Unity version of your new build. I used the last Unity package for my projects and downloaded from Artoolkit website. Could you please let me know how to download new build Unity package? Or if there is no Unity package for the new build, the documents for rebuilding Unity package from scratch.

I read your comments about changing the calibration params in the android build. However, It would be great if you inform me how to set default calibration method for Unity packages without calling the servers params and use the local calibration params. Or mention some documents related to this part and I can work on this part.  

Thanks.

**Comment by ThorstenBux** [comment]
@5y, you hit the weak spot. Yes, we haven't looked into the Unity3D build yet. Meaning you would need to rebuild the Unity3D package by yourself. The documentation for that is here: https://github.com/artoolkitx/arunity5/blob/master/src/Android_Unity_Player_Source/AndroidStudioProj/readme.md
I hope this still works. I'd highly appreciate if you could fix and push back any issues you find while compiling.

Regarding, skipping of the server download I can't tell you out of the top of my head.

**Comment by 5y** [comment]
@ThorstenBux Thank for sharing documents. Sure, I'll try to build the package.

Regarding the server download, it would be great if you let me know any idea or documents, right now I can't find the lines related to getting params from the server in unity package.
