### ISSUE TITLE
what does the 0.5f offset for 3D coord used for in kpmRefDataSet.cpp

### ISSUE THREAD

**Issue by 1474123989** [artoolkit/artoolkit5#351]
hi, in the file kpmRefDataSet.cpp, line 148 and 149, there is an extra 0.5f offset for 3D
 coord, e.g.: (x + **0.5f**) / dpi * 25.4f
I am wondering What it is used for ? What if without the "0.5f"?

**Comment by philip-lamb** [comment]
It places the measurement of the coordinate position in the middle of a pixel, rather than on its left edge.
