### ISSUE TITLE
YUYV usb camera

### ISSUE THREAD

**Issue by wangjl403** [artoolkit/artoolkit5#357]
Hello every i have a problem when using artoolkit5 on rockchip(arch64) or raspberry(armhf).
The camera is a uvcvideo usb camera , 
Linux run ./simpleLite , then the video is error color with some points red and blue，
I want to know this problem how fix, yuyv or rgb" pixeformat ?
Thanks everybody very much

**Comment by philip-lamb** [comment]
There have been a number of recent improvements to the Video4Linux2 video module. My recommendation would be to see if the camera can supply NV21 or 420f format, and use that. The video config string would be "-module=V4L2 -format=0 -palette=NV21". The -format=0 requests that the incoming video is not converted to RGB, and the -palette command is passed to Video4Linux2 to request that format from the camera.

**Comment by wangjl403** [comment]
Thank you : philip
My USB camera output format is YUYV and M-JPEG, I also do that you tell me
ex : sudo ./simpleTest -module=V4L2 -format=0 -palette=NV21   or 
ex : sudo ./simpleTest -module=V4L2 -format=0 -palette=420f
But the problem remains.
So i want to know if i use artoolkit 5, i must code the YUYV converted RGB/BGR or use another camaer(supporting RGB/BGR).

**Comment by philip-lamb** [comment]
M-JPEG output is not currently supported in ARToolKit. But YUYV format is, although it has to be converted to RGBA.

**Comment by growingant** [comment]
Hello:
      We still have camera display problem described above. Our camera supports YUYV format. I checked videoV4L2.c and found that there did have a convert from YUYV to RGB(BGR?). Strangely, the same example simpleLite can work on pc ubuntu, and can not work on our embeded system.
     We have the same problem like this: https://github.com/artoolkit/artoolkit5/issues/319
     Thank you very much!

**Comment by wangjl403** [comment]
hello: 
i have a small question , i found artoolkit5 source code is bind with OpenGL, but i want to build it on my raspberry(with OpenGLES)， so i want to know if i can using the ARToolkit5 on my linux OS nor Android.
very very thank you!
