### ISSUE TITLE
Error message popup when building anything (Windows 10)

### ISSUE THREAD

**Issue by mflux** [artoolkit/artoolkit5#376]
![screenshot 2018-01-10 18 40 46](https://user-images.githubusercontent.com/1041360/34806044-d72141c4-f635-11e7-8fc2-26188b404e71.png)

This pops up as soon as I try to build anything in the SDK.

Possibly related compile errors:

Error	5	error LNK1181: cannot open input file 'opencv_core2410d.lib'	C:\Program Files (x86)\ARToolKit5\VisualStudio\vs120\LINK	calib_camera
Error	6	error LNK1181: cannot open input file 'opencv_core2410d.lib'	C:\Program Files (x86)\ARToolKit5\VisualStudio\vs120\LINK	calib_stereo
Error	4	error LNK1181: cannot open input file 'ARvrmld.lib'	C:\Program Files (x86)\ARToolKit5\VisualStudio\vs120\LINK	simpleVRML
Error	3	error C1083: Cannot open include file: 'Movies.h': No such file or directory	C:\Program Files (x86)\ARToolKit5\lib\SRC\VideoQuickTime\videoQuickTime.c	86	1	ARvideo
Error	1	error C1083: Cannot open include file: 'boost/algorithm/string/predicate.hpp': No such file or directory	c:\program files (x86)\artoolkit5\lib\src\arvrml\arViewer.h	43	1	ARvrml
Error	2	error C1083: Cannot open include file: 'boost/algorithm/string/predicate.hpp': No such file or directory	c:\program files (x86)\artoolkit5\lib\src\arvrml\arViewer.h	43	1	ARvrml

I've installed the SDK via installer and noted that the environment variables have been set correctly. Not sure why I'm getting this error.

**Comment by ThorstenBux** [comment]
Try https://github.com/artoolkitx/artoolkit5 I just updated the windows build stuff there.

**Comment by mflux** [comment]
Thanks. Looks like it'll need VS2017, upgrading and closing for now.
