### ISSUE TITLE
freeglut ERROR while running checkImage example

### ISSUE THREAD

**Issue by srichakradhar** [artoolkit/artoolkit5#381]
I'm running ubuntu 16.04 LTS
```
Using default video config.
libARvideo: GStreamer 0.10.36
libARvideo: GStreamer pipeline is READY!
libARvideo: GStreamer negotiated 320x240@30.000fps
libARvideo: allocating 230400 bytes
libARvideo: GStreamer pipeline is PAUSED.
Image size (x,y) = (320,240)
Camera ID = (00000000, 00000000)
*** Camera Parameter ***
--------------------------------------
SIZE = 320, 240
Distortion factor: k1=0.1147807688, k2=-0.5208189487, p1=-0.0002069871, p2=-0.0040593124
                  fx=337.085815, fy=316.949043, x0=159.148895, y0=118.950233, s=0.993923
339.14696 0.00000 159.14890 0.00000 
0.00000 318.88706 118.95023 0.00000 
0.00000 0.00000 1.00000 0.00000 
--------------------------------------
freeglut  ERROR:  Function <glutCreateWindow> called without first calling 'glutInit'.

```

**Comment by srichakradhar** [comment]
I've checked [checkImage.c](https://github.com/artoolkit/artoolkit5/blob/master/util/1394/checkImage/checkImage.c).
But, I couldn't find any call to `glutInit` or `glutCreateWindow`
I found few references on [StackOverflow](https://stackoverflow.com/questions/26685010/qt-using-freeglut-error-with-glutinit)  and [Ubuntu Forums](https://ubuntuforums.org/showthread.php?t=1616945) but not sure how well they fit in for this issue.

**Comment by ThorstenBux** [comment]
@srichakradhar please check the artoolkitx fork https://github.com/artoolkitx/artoolkit5
and let me know. We continue the project there.
