### ISSUE TITLE
Camera parameter search takes an unreasonably long time

### ISSUE THREAD

**Issue by O-O-Balance** [artoolkit/artoolkit5#386]
I am building an Android app with ARToolKit 5. Without granting it the `INTERNET` permission, things work fine. But with the permission it takes too long (minutes!) until the first marker is detected.
I have looked into this and I believe the problem is the camera parameter search. There is a message in the log:
`Connection timed out after 300000 milliseconds`
A timeout of five minutes seems too long, it should abort the search much sooner. Also, why does the server not respond more quickly?

**Comment by ThorstenBux** [comment]
Head over to https://github.com/artoolkitx/artoolkit5
the new calibration server is added to this code and the timeout won't happen.

**Comment by O-O-Balance** [comment]
Thanks, it works now.
