### ISSUE TITLE
How to read the code?

### ISSUE THREAD

**Issue by skylook** [artoolkit/artoolkit5#39]
I am a student studying AR. Artoolkit is nice but it's a little hard for me to catch all the details from such a large code:)
Is there any paper or document that describe the algorithm? That would be helpful.

**Comment by ThorstenBux** [comment]
There is something in here:
http://artoolkit.org/community/forums/viewtopic.php?f=29&t=9553

Also I'd recommend to continue the discussion in the forum, hence closing this issue now.
