### ISSUE TITLE
AR not working on certain Android devices

### ISSUE THREAD

**Issue by O-O-Balance** [artoolkit/artoolkit5#392]
I am developing an Android app with ARToolKit and for the most part, things are working great. On one particular test device however (a Motorola Moto G5), ARToolKit will not start. The error message is:

`E/libAR: [error] returned error code "-1" starting video capture.`

And further down:

```
I/libAR: [info] Closing ARToolKit video.
E/libAR: [error] Error: cannot close video while frames are still being pushed.
E/libAR: [error] Error closing video.
E/libAR: [error] ARController::androidVideoPush1: ARVideoSource is not running.
```

Since switching to ARToolKitX, I have been initializing ARToolKit like this

`toolkit.startWithPushedVideo(width, height, "NV21", camera_parameters_path, 0, false);`

and I wonder whether it's something to do with that since I had to work out the `"NV21"` part by trial and error. It may however be unrelated.
Any advice would be greatly appreciated.

**Comment by ThorstenBux** [comment]
@O-O-Balance I'm a bit confused on which repo you are using. If you are using artoolkitX repo please open the issue there. Also I believe it has todo with Video API2 which should be solved on artoolkitX

**Comment by O-O-Balance** [comment]
Sorry about opening the issue in the wrong place. Opened a new issue [here](https://github.com/artoolkitx/artoolkit5/issues/148), closing this one.
