### ISSUE TITLE
cnan't open the file :#include "zlib.h"

### ISSUE THREAD

**Issue by dragonflyhe** [artoolkit/artoolkit5#396]
vs in win7,build,error:
cnan't open the file :#include "zlib.h"
help me please!!!

**Comment by ThorstenBux** [comment]
Switch to artoolkitX/artoolkit5 https://github.com/artoolkitx/artoolkit5
and tell me if that works

**Comment by dragonflyhe** [comment]
i have to install vs2017 first！

**Comment by ThorstenBux** [comment]
artoolkitX repo please. use the issues there I'll answer
