### ISSUE TITLE
how to find a easy way to install openscenegraph on Mac?

### ISSUE THREAD

**Issue by tyoli** [artoolkit/artoolkit5#398]
http://www.artoolkit.org/dist/openscenegraph/ i find the install package yet, and easy to use.but I don't find  a easy way to install it in Mac now,or no found a install package with openscencgraph in www.artoolkitx.org.

**Comment by ThorstenBux** [comment]
maybe that helps https://github.com/OGStudio/openscenegraph-cross-platform-guide/tree/master/1.4.InstallUnderMacOS
