### ISSUE TITLE
Artoolkit for android

### ISSUE THREAD

**Issue by mhmughees** [artoolkit/artoolkit5#52]
I copy whole code base of **ARToolkit** and try to run android studio **examples** but each example just crashed on start. Than I download **android sdk bundle** from Artoolkit website, in this only eclipse examples are included so I migrate it into android studio(using default android studio migration). Now **ARSimple** is running but for any example including native code it gives linking error. For exaple for **ARSimpleNativeCars** i got the following error while making in android studio.

`Error:(49, 24) AR/gsub_es.h: No such file or directory`

**Comment by Mostafa-Shoir** [comment]
i have the same problem
please , can anyone helps us

**Comment by BoiseBaked** [comment]
Please give me the easily scenario to try to reproduce. So you cloned the repo artoolkit5, an on the master branch you tried to build and deploy which Android Studio example app. What did you try to deploy it to? What did the crash log say was the source of the crash?

We really want everybody to start using Android Studio. The Eclipse projects will be gone soon. So let's get the Android Studio example projects back and running.

**Comment by BoiseBaked** [comment]
So everything seems to be working for me on Mac OS X.
Did you remember for the repo case to go into directory called "[repo root]/android" and from the command line, fire off "./build.sh" followed by "./build_native_examples.sh".

Both these scripts build different dependencies for two different sets of the example apps. But only build.sh builds the ARToolKit libraries dependencies. So for the build_native_examples.sh set of example apps, you have fire off build.sh first. We probably should fix that.

I do not know why the downloadable SDKs links are not up-to-date. I'll bring that up.

Now if you're using the Windows dev env, there might be something broken there. Please let me know.

**Comment by Mostafa-Shoir** [comment]
thanks for interest,
firstly, i'm using android studio
when i open any project i don't get build app in the project, so i can't make run project, please tell me how to i fix this problem ?

**Comment by thielsn** [comment]
One problem is, that some directories are not named exactly like specified in settings.gradle.
E.g.: artoolkit5/AndroidStudioProjects/ARMarkerDistanceProj$ mv aRMarkerDistance ArMarkerDistance

... helped to make ARMarkerDistanceProj compile under Linux.

**Comment by BoiseBaked** [comment]
Mostafa-Shoir, I need to know if using Android Studio on Mac OS X or Windows. And if Windows which Windows: Windows 10 or Windows 8.1.

Also, before you can successfully build and deploy one of the ARTK5 example apps using Android Studio, you have first build and place the dependencies for the AS example app project by doing this: on Mac OS X, for the repo case, go into directory called "[your ARTK5 repo root]/android" directory and from the command line, fire off "./build.sh" followed by "./build_native_examples.sh". There may be a problem with the batch build scripts for Windows. If you get errors from that, your dev platform has a setup issue. Refer to [your ARTK5 repo root]/AndroidStudioProjects/Docs/AS_Migration.pdf.

thielsn, we don't overtly support Android development with Android Studio on Linux. Just Mac OS X or Windows but I don't see why it wouldn't work given the similarity between Mac OS X and Linux. I'll have to checkout project/module naming thing get that fixed.

**Comment by Mostafa-Shoir** [comment]
Boise Baked , i'm using Android Studio on Windows 7.
1- when i opened the project ARSimpleNativeProj showed this msg ( Error:Unknown host 'downloads.gradle.org'. You may need to adjust the proxy settings in Gradle.
href="https://docs.gradle.org/current/userguide/userguide_single.html#sec:accessing_the_web_via_a_proxy">Learn about configuring HTTP proxies in Gradle ) .
2- then i don't get build app in the project so i can't make run project.

**Comment by Mostafa-Shoir** [comment]
thanks Boise Baked
i fix that all wrong but when i run app just crashed , that's error 
java.lang.UnsatisfiedLinkError: Couldn't load c++_shared from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.artoolkit.ar.samples.ARSimpleNative-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.artoolkit.ar.samples.ARSimpleNative-1, /vendor/lib, /system/lib]]]: findLibrary returned null

**Comment by BoiseBaked** [comment]
Mostafa-Shoir, I think it's time for you to upgrade to Windows 10. We have never tested Android Development with Android Studio on Windows 7 and never will. Also, the fact that your getting a link error from not finding libc++_shared.so is telling me either the build script isn't building or you're gradle plugin for the AS IDE isn't right. Android development with the AS IDE is complicated by the fact that AS doesn't cleanly support the Android NDK (native C/C++) development yet. I will find some time today and attempt to build and deploy the Android ARSimpleNative app to an actual device.

**Comment by huangdibaba** [comment]
hello, BoiseBaked
When I was try to finish the module **ARTK SDK Download, Installation and Setup** in file which called "Docs" . There is a problem and the err message is showed below. PS: I build it on Win8.1.
(git bash here)
$ ./build.sh
Working from directory "/e/Study/AndroidStudy/artoolkit5/android".
./build.sh: line 143: /ndk-build: No such file or directory

**Comment by huangdibaba** [comment]
hello, BoiseBaked
When I was try to finish the module ARTK SDK Download, Installation and Setup in file which called "Docs" . There is a problem and the err message is showed below. PS: I build it on Win8.1.
(git bash here)
```
$ ./build.sh
Working from directory "/e/Study/AndroidStudy/artoolkit5/android".
./build.sh: line 143: /ndk-build: No such file or directory
```
