### ISSUE TITLE
Does not detect multiple pattern in NFT

### ISSUE THREAD

**Issue by atoyk** [artoolkit/artoolkit5#6]
At ARMovie(Eclipse Project), I add a pattern file(fset/fset3/iset) information in assets/Data/markers.dat and patt.fset/fset3/iset in assets/DataNFT, but dose not detect the added patt iamge.
Although patt image of page 0 is detected,  patt iamge of after the page1 is not detected, returned "Detected page 0".

patt.fset/fset3/iset it was created by genTexData.exe.

Swapping the order of the pattern file, and then only  detect patterns of page 0.

**Comment by atoyk** [comment]
Additional information.

I think it was investigated, and kpmMatching.cpp of kpmSetRefDataSet () and kpmMatching () is wrong.

1.kpmSetRefDataSet ()
processing to add kpmHandle-> refDataSet to FreakFeaturesAndDescriptors

// Org.
if (kpmHandle-> refDataSet.refPoint [i] .refImageNo == kpmHandle-> refDataSet.pageInfo [k] .imageInfo [m] .imageNo) {
// Chg.
if (kpmHandle-> refDataSet.refPoint [i] .refImageNo == kpmHandle-> refDataSet.pageInfo [k] .imageInfo [m] .imageNo
&& KpmHandle-> refDataSet.refPoint [i] .pageNo == kpmHandle-> refDataSet.pageInfo [k] .pageNo) {

2.kpmMatching ()
matched_image_id does not depend on the page. But it's calling the kpmUtilGetPose_binary () with the same ID.
I think the result is required for each page.

**Comment by VladVuk** [comment]
Hello Atoyk,

I have the same issue you described.
Also I folowed your suggestions in the code and it seems to me that you are on good track.
I would like to recompile libKPM.a from the source (which would include rewritten kpmmatching.cpp according to your suggestion).

Did you succeed to compile libKPM.a ? 
If so, can you explain how did you compile libKPM.a from source files?

I am using Eclipse on Windows with Artoolkit for Android.

**Comment by atoyk** [comment]
Hello, VladVuk.

Thank you for your comment.
I succeeded to compile from changed sourse code (I get the original source code from this site).
I changed kpmmatching.cpp and kpm.h.
I added Struct to save relation between a page(image) and a database ID in kpm.h.

I am using cygwin for build (.a) and Eclipse for APK (and .so) on Windows, with Artoolkit for Android.

**Comment by VladVuk** [comment]
Hello, Atoyk,

thank you for your suggestion regarding compile process.
I succeeded to compile kpmmatching.cpp and libKPM.a and later NFTSimple project as you wrote.

If I add code ( "&& KpmHandle-> refDataSet.refPoint [i] .pageNo == kpmHandle-> refDataSet.pageInfo [k] .pageNo" ) from your 1st post into kpmmatching.cpp NFTSimple still cannot keep tracking and recognizing the 2nd NFT Marker.

Can you please share or explain in deep your full updates in kpmmatching.cpp and kpm.h for multi NFT marker tracking.
If you can send me files my email is : vlatko.vukovic@gmail.com
Thanks,
Vlad

**Comment by deight** [comment]
I have the same problem, did you manage to fix it in the end? Since i am new to artoolkit i have not a clear idea on what i should do to fix this.

**Comment by VladVuk** [comment]
Yes I succeeded it as well. My solution is temporary and not good one
therefore maybe atoyk can suggest exactly the structure and alloc / delete
of objects where it should be.
I can explain my way...

I have another question.
Is it possible to make loading NFT Markers faster or is it possible to have
markers within application somehow always preloaded into KPM and other
structures in order to make starting Activity faster and update nft markers
dynamically ?

**Comment by dk00891** [comment]
Hi atyok,delight,Vladvuk

Thanks for providing solutions.

I am trying to create multi NFT marker tracking application. I have followed suggestion provided by delight. i need more details to solve this problem.

As explained by delight, In step-1, I have created  int array "pageIDs" in _KpmHandle struct of file kpmPrivate.h
In step 2, should I use imagenum or Pageno to initialize  the int array "pageIDs", as in step-3, pageNo are being assigned from created int array. 

can you share and explain, more details regarding this solution.my email id is:dk00891@gmail.com

I think solution can also be submitted to Philip, to resolve this issue permanently. 

Thanks,
DK

**Comment by stained** [comment]
Thanks all, definitely going in the right direction! Based on all of the above I have the following that seems to work (once compiled and imported into Unity OSX at least):

## kpmPrivate.h

line 45 (below the #endif): 
`#define DB_IMAGE_MAX 1024    // max number of images across all pages, adjust as necessary`

line 94 (within the _KpmHandle struct):  
`    int                       pageIDs[DB_IMAGE_MAX];`

## kpmMatching.cpp

### kpmSetRefDataSet() function:

line 272 (just below int db_id = 0;):

`        kpmHandle->pageIDs[DB_IMAGE_MAX - 1] = {0};`

line 280 (add to if (kpmHandle->refDataSet.refPoint[i].refImageNo ==... statement):

` && kpmHandle->refDataSet.refPoint[i].pageNo == kpmHandle->refDataSet.pageInfo[k].pageNo`

line 293 (just below ARLOGi("points-%d\n", points.size());): 

`                kpmHandle->pageIDs[db_id] = kpmHandle->refDataSet.pageInfo[k].pageNo;`

### kpmMatching() function:

line 667 (just below kpmHandle->result[pageLoop].inlierNum = (int)matches.size();):

`                kpmHandle->result[pageLoop].pageNo = kpmHandle->pageIDs[matched_image_id];`

**Comment by jorgecr** [comment]
hey dudes, super usefull, very thanks!!!!!

**Comment by FalkoGit** [comment]
Hello to everyone, I changed the files stained suggest, but I don't know how to compile it, and insert the modification in eclipse project (nftsimple or nftbook) Can anyone get me step by step instructions, since i'm a newbie in cpp and java project integration, thanks a lot to anyone that can suggest a way to make it works.

**Comment by wallywyyoung** [comment]
Hey Folks! If you think you've fixed this issue, would you like to submit a pull request? =)

**Comment by Jickelsen** [comment]
Yes, please do! I was using the older 5.2.1 Unity plugin for tracking multiple NFT markers in the same scene, but even though tracking is fine I've found detection to be much worse than the newer NFT library (the target image needs to get very close to the camera). Doesn't seem very useful to submit issues regarding older versions though.

**Comment by Jickelsen** [comment]
@FalkoGit I am also a newbie but the relevant documentation is in https://github.com/artoolkit/artoolkit5/blob/master/AndroidStudioProjects/Docs/AS_Migration.pdf

You want to run build.sh (or build.bat if you run Windows) in the android folder of the project. Make sure you've downloaded the Android NDK and set an $NDK environment variable to the download location first. I'm using Unity and after that I simply dropped the two .so libraries from the armeabi-v7a folder in libs to the appropriate Android plugins folder in the Unity project, replacing the files already there.

For iOS and OSX the necessary ARWrapper.bundle was simply a build target using the XCode project file supplied in this repo.

**Comment by FalkoGit** [comment]
Thanks, I'm going to try that.

**Comment by wallywyyoung** [comment]
@Jickelsen My mistake, I thought you'd done this using the new libKPM on 5.3.x =).

**Comment by sirmagid** [comment]
its not work

**Comment by sasuke777** [comment]
In nftSimple. I want to recognize the marker at the same time, also, I want to display the CG at the same time, but it does not go well. How Could you tell me whether can it?

**Comment by wallywyyoung** [comment]
Hey everybody! Took your changes, and they work! They will be included in 5.3.2's release. Keep in mind, that you need to turn on Multi NFT mode to see Multi NFT working. Special thanks to @stained for comprehensive documentation and @atoyk for finding the answer.

**Comment by codefull** [comment]
Thanks a lot for this answer, I've got the entire weekend trying to figure out how that happened racking my brain because I had no internet access. You people saved me and  my time. I'm new to Android, so SDK and NDK with native development is a real breakthrough when using this NFT library. Thanks a lot people, special thanks to  @stained and @atoyk .

**Comment by kayrumet** [comment]
where i activate multi NFT mode?

**Comment by VladVuk** [comment]
Check nftsimple sample. Read artoolkit documentation on The web.
With arsimple/arbase lib YOU can Use nft markers as Well.
There IS nothing special in starting nft mode.
Just put nft markers in assets (datanft subdirectory) and in markers.dat in
assets/Data/ put proper info for each nft marker and IT should work using
armarkernft.cpp as shown in nftsimple example.


utorak, 5. travnja 2016. korisnik kayrumet <notifications@github.com>
napisao je:

**Comment by kayrumet** [comment]
hi
 i have the nftbook for android in eclipse, from the package Artoolkit 5.3.2 y add a new marker to markers.dat and put the proper info of the marker in folder assets/data. When i run the apk in my phone the model show for the first marker in markers.dat. For the other not show, sometime the model show like a blink, why this happen????

**Comment by codefull** [comment]
If you are still stopped in this example come to see me at my lab.
Ernesto

2016-04-06 9:32 GMT-07:00 kayrumet <notifications@github.com>:

**Comment by VladVuk** [comment]
IT should work with 5.3.2.

Please explain what happens a little bit more.

Nftbook Use those simple markers.
Did you for example changed resolution Of camera to 640x480 (with settings)
or is IT still default 320x240. If that is The case hiro marker could work
Well but nftmarker not so good.
Be sure to kill and restart nftbook after changing resolution.


srijeda, 6. travnja 2016. korisnik codefull <notifications@github.com>
napisao je:

**Comment by kayrumet** [comment]
NFTbook(android with eclipse) work with pinball marker, i add an other marker (gibraltar) and compile.
../DataNFT/gibraltar
NFT
FILTER 15.0

../DataNFT/pinball
NFT
FILTER 15.0
when i execute the apk the the app detect good the gibraltar marker but not the pinball marker, with the pinball marker some time show me the plane model, but for less that one second, like a blink, the rest of the time don't show me nothing.

**Comment by codefull** [comment]
That is because you need to apply the patch/solution posted by
(*@stained <https://github.com/stained> * commented on 19 Nov 2015
<https://github.com/artoolkit/artoolkit5/issues/6#issuecomment-158238415>)
and recompile artoolkit for android. This should fix your problem look at
this commit (
https://github.com/Jickelsen/artoolkit5/commit/92019d5a93067fdbf5e12f9e436fcc2a1c18881c).
Here you can find the relevant solution you need.

2016-04-06 12:21 GMT-07:00 kayrumet <notifications@github.com>:

**Comment by densetsughem** [comment]
anyone still has a copy of artoolkit5 windows installer?

**Comment by ThorstenBux** [comment]
https://archive.artoolkit.org/download-artoolkit-sdk

**Comment by densetsughem** [comment]
Thanks for the link. 

But it is not working now: Bad Request
http://www.artoolkit.org/dist/artoolkit5/5.3/ARToolKit5-bin-5.3.2r1-Linux-x86_64.tar.gz?_ga=2.54311784.1370065518.1497351590-511434340.1495703385

**Comment by ThorstenBux** [comment]
ok, will investigate

**Comment by ThorstenBux** [comment]
here you go: https://archive.artoolkit.org/dist/

**Comment by densetsughem** [comment]
thanks.

is nftmarker working in android mobile browser? when i tried to use the pinball and the same code example the 3d does not show in mobile browser?

**Comment by ThorstenBux** [comment]
In the browser? ARToolKit5 on android requires you to develop an app to get AR to work. JSARToolKit works from the browser but not with NFT as of now.

**Comment by ashms1995** [comment]
Hey guys, thanks a lot for such great efforts and simplified explanation.
As you guys mentioned above, the multi-nft feature works. But a single object is augmented for the detected nft marker. When next marker is detected, next marker is augmented. I want to augment multiple objects at the same time but that is not working. Please help me regarding the same! Any kind of help is appreciated! Thank you!

**Comment by xingguo3** [comment]
Thanks all for your answers. Is anyone know how to track multi NFT markers in iOS app. I saw all the codes showing above are already in certain files in iOS source code. However, I can only track 1 NFT marker at a time.

**Comment by ThorstenBux** [comment]
@xingguo3 would you consider switching to artoolkitX? https://github.com/artoolkitx/artoolkitx

**Comment by xingguo3** [comment]
Thanks for your reply. Does it support multi-NFT tracking. If yes, I;m sure
to switch to artoolkit X. Thanks again!

**Comment by ThorstenBux** [comment]
Even better, artoolkitX has a new texture tracker that allows you to simply use JPGs as trackables.

**Comment by xingguo3** [comment]
wow thks a lot. but i think when i woke up this moring, it.seems that
suddenly i jv found the solution to multi–nft tracking in v5.3 package.
anyway, thks for ur help. i'll certainly try artoolkit.X in the future!

Thorsten Bux <notifications@github.com> 于 2018年4月4日周三 上午2:46写道：
