### ISSUE TITLE
Unity iOS build fails with missing function arwSetLogLevel

### ISSUE THREAD

**Issue by bdilday** [artoolkit/artoolkit5#65]
With Unity SDK 5.3.1r2, Unity 5.3.1f1

```
Undefined symbols for architecture armv7:
  "_arwSetLogLevel", referenced from:
      RegisterMonoModules() in RegisterMonoModules.o
ld: symbol(s) not found for architecture armv7
```
It looks like arwSetLogLevel is not being built into the ARWrapper static library.

**Comment by ViggoV** [comment]
I am having the same issue. Any help would be much appreciated!

**Comment by teunsteenbekkers** [comment]
Same here, it happens (to me at least) when opening the "Application Options" on the ARController in Unity 5.3.3f1 Personal.

Sometimes a similar error appears mentioning the "arwStartAR" method.

**Comment by cwhitney** [comment]
Same problem. Rebuilt from the latest github and still the same. Unity 5.3.1f1

ndefined symbols for architecture armv7:
  "_arwSetLogLevel", referenced from:
      _PluginFunctions_arwSetLogLevel_m_439961714_0 in Bulk_Assembly-CSharp_0.o
      _ARNativePluginStatic_arwSetLogLevel_m_1915368353_0 in Bulk_Assembly-CSharp_0.o
      _PluginFunctions_arwSetLogLevel_m_439961714_0 in Bulk_Assembly-CSharp_0.o
      _ARNativePluginStatic_arwSetLogLevel_m_1915368353_0 in Bulk_Assembly-CSharp_0.o
     (maybe you meant: _PluginFunctions_arwSetLogLevel_m_439961714_0, _ARNativePluginStatic_arwSetLogLevel_m_1915368353_0 , _ARNativePlugin_arwSetLogLevel_m1049969809_0 )
ld: symbol(s) not found for architecture armv7

**Comment by razanmjn** [comment]
I am having same issue. Any help would be highly appreciated.

**Comment by ThorstenBux** [comment]
Hi there,

are you still having this issue with the new release (5.3.2)?

**Comment by teunsteenbekkers** [comment]
Hello,

I am not having this issue anymore, no. Thanks for asking.
