### ISSUE TITLE
NFT

### ISSUE THREAD

**Issue by amaiaespinosa** [artoolkit/artoolkit5#69]
Hi!
i am working with ARToolKit in Unity 5.3.2 and ARToolKit 5.3.1. I am trying to run NFTMultiMarker example, but it doesnt work. Could anyone help me?¿

**Comment by cwhitney** [comment]
This was actually fixed here: https://github.com/artoolkit/artoolkit5/issues/6  It's in the repo, but not part of an official release yet. You can build it and it will work though.

**Comment by amaiaespinosa** [comment]
Hi!

Thank you so much for the information.
I really need the Unity plugin so please notify me when the error fix. I 
have to tell you that i am working with a Unity plugin for mac Wally 
Young send me (another different than in the web because it was an error 
for MAC, and Wally fix it to me). So i will need these plugin with the 
NFT utility working.
So please notify me as soon as everything working.

If the error is in some script and not in the native code, please tell 
me, and i will fix it.

Thank you so much for all of your support.

Amaia Espinosa

**Comment by ckcdavid** [comment]
Hi, we are facing the same problem.
Hope the fix for Unity plugin will release soon.

**Comment by ThorstenBux** [comment]
@amaiaespinosa, @cwhitney , @ckcdavid 
New ARUnity release is out and I just ran the TwoNFTMarkerScene example (as I think you refer to that)

For me it worked, this is why I close this now as fixed. Feel free to come back to me if there is still an issue.
