### ISSUE TITLE
ARToolKit for Android. mk_patt.exe doesn't work

### ISSUE THREAD

**Issue by MyDogTom** [artoolkit/artoolkit5#7]
Hi. I downloaded ARToolKit for Android. I cannot launch mk_patt.exe. It says pthreadVC2.dll is missing.  Should I download and install other packages (eg. Windows (Visual Studio 2013)) ?
PS. I have Windows 7 64-bit Professional Service pack 1

**Comment by MyDogTom** [comment]
I found, that Android package is missing some required dll. I installed Windows package. It contains similar `bin` folder with required dll. Now `mk_patt.exe` works.

**Comment by philip-lamb** [comment]
Fixed in ARToolKit for Android v5.3.1.
