### ISSUE TITLE
Create single multiple markers.

### ISSUE THREAD

**Issue by VikasSinghaiAndroid** [artoolkit/artoolkit5#72]
Hi,

I want to create 1000 marker for detection and I want to get detected marker id. All this I want for device marker detection, I don't want to use any cloud server.

Please let me know how I can create 1000 markers and how I can get detected marker id,

I am using ARBaseLib(ARToolKit5-bin-5.3.1-Android).

Regards,
Vikas

**Comment by philip-lamb** [comment]
Please post questions on the forum.

**Comment by VikasSinghaiAndroid** [comment]
Hi Philip,

I posted this question on form but no one replayed, can you please tell me
the solution for this.

How I can create 1000 markers and how i can get marker ID, i am developing
application for android mobile, I am using ARBaseLib.For device based
marker recognition.

Thanks in advance.


Regards,

Vikas Singhai
