### ISSUE TITLE
ARWrapper.dll not found

### ISSUE THREAD

**Issue by ashokbugude** [artoolkit/artoolkit5#80]
Hi

I have unity installed in windows 7 , created the setup file , included all dll files, works fine

When I install the same in windows 8 , where unity is not installed .I get ARWrapper.dll not found when i run the application. I have installed vcredist_64.exe in windows 8 . Since Unity is not installed, I have placed the dll files in c:/windows/system32 location where cmd.exe is present. But the errors still persist
Pls help to resolve the issue

**Comment by philip-lamb** [comment]
For deployed executables, DLLs must be placed alongside the .exe file. Again, this is outside the scope of ARToolKit.

**Comment by ashokbugude** [comment]
Hi

I have placed it along with the executable application,but still get the
same error.

**Comment by ashokbugude** [comment]
Hi

Can I know whom do I ask to get the issue resolved

Thanks

**Comment by ThorstenBux** [comment]
Please try installing the MS redistributable package from here:
http://www.artoolkit.org/dist/arunity5/5.3/ARUnity5-5.3.2-tools-win.zip

Solved the issue for me.

I admit the error message is very misleading.

**Comment by ashokbugude** [comment]
I have installed it, but the issue still persists
