### ISSUE TITLE
missing libjpeg for Windows 10 UWP

### ISSUE THREAD

**Issue by danglingneuron** [artoolkit/artoolkit5#84]
I tried compiling the toolkit for windows 10 UWP and a final road block is the external dependency libjpeg.
I am not a C++ developer so maybe I am missing something trivial.

I need to know how the team compiled libjpeg for Windows 8.1 (RT) so I can follow suit and take similar steps for Windows 10 UWP. Also which source was used for libjpeg.

**Comment by philip-lamb** [comment]
libjpeg was built directly for WinRT 8.1 from the MSOpenTech OpenCV port. URL: https://github.com/Microsoft/opencv

Since MSOpenTech has been folded back into Microsoft, and their OpenCV work merged into the OpenCV mainline, it would be good to track it directly.

**Comment by ThorstenBux** [comment]
I'm closing this now as answered but feel free to open it again if you have more questions.

**Comment by banjoanders** [comment]
@danglingneuron Did you succeed in compiling for UWP? What steps did you take to update the project(s) in Visual Studio?
