### ISSUE TITLE
Linux Binaries 5.3

### ISSUE THREAD

**Issue by stefanhuber** [artoolkit/artoolkit5#86]
Is there a reason, why there are no linux binaries for version 5.3 and 5.3.1 ?

**Comment by Neuroforge** [comment]
Hello Stefan,

The Linux binaries can be found at this link.

http://www.artoolkit.org/dist/artoolkit5/5.3/

Regards,

Daniel

**Comment by ThorstenBux** [comment]
Solved with new release
