### ISSUE TITLE
Fix Android.mk  error

### ISSUE THREAD

**Issue by carset** [artoolkit/artoolkit5#9]
diff --git a/android/jni/Android.mk b/android/jni/Android.mk
index 5804316..50f8a50 100644
--- a/android/jni/Android.mk
+++ b/android/jni/Android.mk
@@ -246,10 +246,10 @@ include $(BUILD_STATIC_LIBRARY)
 include $(CLEAR_VARS)
 LOCAL_PATH := $(MY_LOCAL_PATH)
 CURL_DIR := $(MY_LOCAL_PATH)/curl
-MY_FILES := $(wildcard $(ARTOOLKIT_ROOT)/lib/SRC/video/*.c)
-MY_FILES += $(ARTOOLKIT_ROOT)/lib/SRC/videoAndroid/videoAndroid.c $(ARTOOLKIT_ROOT)/lib/SRC/videoAndroid/cparamSearch.c $(ARTOOLKIT_ROOT)/lib/SRC/videoAndroid/nxjson.c $(ARTOOLKIT_ROOT)/lib/SRC/videoAndroid/sqlite3.c
-MY_FILES += $(wildcard $(ARTOOLKIT_ROOT)/lib/SRC/videoDummy/*.c)
-MY_FILES += $(wildcard $(ARTOOLKIT_ROOT)/lib/SRC/videoImage/*.c)
+MY_FILES := $(wildcard $(ARTOOLKIT_ROOT)/lib/SRC/Video/*.c)
+MY_FILES += $(ARTOOLKIT_ROOT)/lib/SRC/VideoAndroid/videoAndroid.c $(ARTOOLKIT_ROOT)/lib/SRC/VideoAndroid/cparamSearch.c $(ARTOOLKIT_ROOT)/lib/SRC/VideoAndroid/nxjson.c $(ARTOOLKIT_ROOT)/lib/SRC/VideoAndroid/sqlite3.c
+MY_FILES += $(wildcard $(ARTOOLKIT_ROOT)/lib/SRC/VideoDummy/*.c)
+MY_FILES += $(wildcard $(ARTOOLKIT_ROOT)/lib/SRC/VideoImage/*.c)
 MY_FILES := $(MY_FILES:$(LOCAL_PATH)/%=%)
 # ARToolKit libs use lots of floating point, so don't compile in thumb mode.
 LOCAL_ARM_MODE := arm

**Comment by philip-lamb** [comment]
Fixed in master in https://github.com/artoolkit/artoolkit5/commit/c7c074d2085bb1a6ec437dbe87e08cb671067477 and 5.2 in https://github.com/artoolkit/artoolkit5/commit/5552a7a417e1bdb0cc56cc8cbd76f56b0ec81424
