### ISSUE TITLE
API to avoid network communication calls for android Camera Calibration service.

### ISSUE THREAD

**Issue by VikasSinghaiAndroid** [artoolkit/artoolkit5#90]
If User wants to avoid network calls, implement new API in android ARBaseLib Library based on flag user can decide Whether he wants to make any network while using ARToolkit android Library.

**Comment by ThorstenBux** [comment]
Hi @VikasSinghaiAndroid:

the call to the calibration service is located in this file: https://github.com/artoolkit/artoolkit5/blob/master/lib/SRC/Video/cparamSearch.c

And then compiled for the usage on Android.

Starting from the ARWrapper you might be able to pass along a parameter that stops the call to the online service if you really want to. 
However that would leave you and your app without proper camera calibration and would probably lead to a bad tracking experience. 

I might be wrong but I don't see this implemented any time soon from us. Hence I'm closing the issue now. However if you figured out how to do it and still got a good tracking we would appreciate your contribution.

Best
