### ISSUE TITLE
how I can change the marker

### ISSUE THREAD

**Issue by jvengador** [artoolkit/artoolkit5#91]
Hello friends, how I can change the natural featured marker in the nftSimple example, with ArtoolKit 5.x and Eclipse.

**Comment by ThorstenBux** [comment]
Eclipse is deprecated now, so I'd advise you to switch to AndroidStudio.

There you can exchange the maker by editing the markers.dat file inside the assets folder of the project.
In the marker.dat you change the path from the current '../DataNFT/pinball' to your maker.

Infos on how to train new NFT markers can be found here: 
http://www.artoolkit.org/documentation/doku.php?id=3_Marker_Training:marker_nft_training

**Comment by hienbx94** [comment]
@jvengador 
if you want change marker dynamic, you need change marker in folder cache of application.
I try it and success

**Comment by ThorstenBux** [comment]
@jvengador: did we solve your issue?

**Comment by ThorstenBux** [comment]
As we got no further reply I'm closing this as solved.

Please feel free to ping me again with further questions.

**Comment by jvengador** [comment]
thank for you help friends...

**Comment by meghalD** [comment]
I am using ARToolKit 5.3.2 and facing an issue while changing the image marker as I am not able to read .dat file also as the link http://artoolkit.org/documentation/doku.php?id=3_Marker_Training:marker_nft_training  mentions about ARToolKitNFT directory; I can't find it and genTextData don't run for me. 
Is there any other solution or I am doing something wrong ?

**Comment by meghalD** [comment]
![gentextdata](https://cloud.githubusercontent.com/assets/22214794/18575785/088e5368-7bf9-11e6-9db1-3100a5c839b9.png)

**Comment by ThorstenBux** [comment]
Hi you tried to run 'genTextData' you need to run 'genTexData'. It is Tex without the 't'.

Please specify your question about the .dat file a bit more.

**Comment by meghalD** [comment]
yes i got the mistake now. Thank you and i am able to make iset for images
now.

For ARMovie I am not able to change the video size. The video size changes
as per the resolution of image and appears quite small for user to see. I
want it to be on the entire android screen always.Please guide how to
resolve this issue.

Thanking you

**Comment by ThorstenBux** [comment]
Hi @meghalD 

please move that to the forum as question. We try to only track issues here.

http://artoolkit.org/community/forums/index.php

**Comment by florenceafrodit** [comment]
I have a problem with getTexData, it does't want to make .iset file. 
![error](https://cloud.githubusercontent.com/assets/25133226/26541518/48461cf4-4456-11e7-9cae-0e9a39ef1201.png)

**Comment by ThorstenBux** [comment]
As regular user you don't have write access to anything located in the 'Program Files (x86)' directory. Please move the ARToolKit5 SDK into your home-directory and try again.
