### ISSUE TITLE
/home/synerzip/Android/android-ndk-r10e/ndk-build all  Android NDK: ERROR:jni/Android.mk:ar2: LOCAL_SRC_FILES points to a missing file     /home/synerzip/Android/android-ndk-r10e/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop. Android NDK: 

### ISSUE THREAD

**Issue by bipinsynerzip** [artoolkit/artoolkit5#97]
/home/synerzip/Android/android-ndk-r10e/ndk-build all 
Android NDK: ERROR:jni/Android.mk:ar2: LOCAL_SRC_FILES points to a missing file    
/home/synerzip/Android/android-ndk-r10e/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
Android NDK: Check that jni/../../../android/obj/local/armeabi/libar2.a exists  or that its path is correct

**Comment by bipinsynerzip** [comment]
I am trying to run ARMovie Example from Eclipse project..

**Comment by hienbx94** [comment]
@bipinsynerzip 
You need edit ```LOCAL_SRC_FILES``` in file Android.mk to folder contain ```SDK AR for android.```

**Comment by bipinsynerzip** [comment]
@hienbx94 
I have searched this whole folder(artoolkit5-master.zip) for this file libar2.a but  i couldn't find it

**Comment by hienbx94** [comment]
@bipinsynerzip 
Please go to [http://artoolkit.org/download-artoolkit-sdk](url) and download ARToolKit SDK for Android.
Then open ``` ARMovie Example``` and edit ```LOCAL_SRC_FILES``` in ```Android.mk file``` to folder ```ARToolKit SDK for Android```.
Then run ndk-build.

**Comment by bipinsynerzip** [comment]
@hienbx94 
Ok I will do it once again lets see.. ..
Thank You man!!

**Comment by bipinsynerzip** [comment]
I have actually downloaded the SDK then it all worked for me.. Thanks you @hienbx94
